### ISSUE TITLE
fetch/undici segment time removed from parent segment

### ISSUE THREAD

**Issue by siosphere** [newrelic/node-newrelic#1787] opened 2023-09-25 21:59 UTC
## Description
We upgraded our NR agent to 11.1.0 to enable fetch/undici segments, those are now appearing, however any custom segments we have, that wrap fetch calls, are no longer including the fetch segment time.

I.E. if we have:
```
newrelic.startSegment(
            'LockedContentSDK.getDocumentInfo',
            true,
            async () => {
                const apiResponse = await fetch(....)
                const response = await this.handleStandardResponse(apiResponse)
                return response.json()
            },
        )
```

We will see a segment for the fetch call, with say 100ms, but the LockedContentSDK.getDocumentInfo will only report 1.2ms

This throws off a bunch of dashboards, and also is confusing

## Expected Behavior

Segments should include the time of its child segments, i.e. creating a custom segment around fetch calls should include the time spent in the fetch call

## Steps to Reproduce

Create a custom segment that wraps a fetch call, only the time spent outside of fetch is reported for that custom segment.

## Your Environment

Node: 18.15.0
NewRelic: 11.1.0

**Comment by bizob2828** [comment] 2023-10-09 17:22
@siosphere I cannot reproduce this.  Do you mind providing a reproduction case?

You can see here the fetchParent segment is wrapping the entire httpbin.org call
<img width="1330" alt="screenshot 2023-10-09 at 1 20 43 PM" src="https://github.com/newrelic/node-newrelic/assets/1874937/0afa8a39-7082-4a7a-9540-3b406b378900">


Here's what I did

```js
const newrelic = require('newrelic')
const express = require('express')
const app = express()
const { PORT = 3000 } = process.env

app.get('/named-route', (req, res) => {
  newrelic.startSegment('fetchParent', true, async() => {
    const response = await fetch('https://httpbin.org/anything')
    const data  = await response.json()
    res.send(data)
  })

})

app.listen(PORT, () => console.log(`Example app listening on port ${PORT}!`))
```

**Comment by bizob2828** [comment] 2023-10-24 16:28
@siosphere I'm closing this because I cannot reproduce. If you can provide a reproduction case, please reopen

**Closed by bizob2828** 2023-10-24 16:28 UTC
Labels: bug, cannot reproduce
