### ISSUE TITLE
TypeError: newrelic.setTransactionName is not a function

### ISSUE THREAD

**Issue by doliG** [newrelic/node-newrelic#474] opened 2020-09-08 12:41 UTC
Hello,

I'm trying to run newrelic on a **TypeScript** server which is rendering angular application (**ng Universal**).

Since angular 9 migration, we can't use use newrelic anymore, because we got the error `TypeError: newrelic.setTransactionName is not a function`.

## Description

[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT share sensitive information, whether personal, proprietary, or otherwise! )

Here's a code sample:

```ts
// Other imports...
import * as express from 'express';
import * as newrelic from 'newrelic';

// Stuff...

server.get('/', (req, res, next) => {
    newrelic.setTransactionName('angular/home');
    angularHandler(req, res, next);
});
```

```
# Runtime error
TypeError: newrelic.setTransactionName is not a function
    at server.get (dist/server/us/main.js:10:7376209)
    at Layer.handle [as handle_request] dist/server/us/main.js:10:4081161)
    at next (dist/server/us/main.js:10:3811678)
    at Route.dispatch (dist/server/us/main.js:10:3811707)
    at Layer.handle [as handle_request] (dist/server/us/main.js:10:4081161)
    at dist/server/us/main.js:10:7850903
    at Function.process_params (dist/server/us/main.js:10:7852283)
    at next (dist/server/us/main.js:10:7850802)
    at module.exports (dist/server/us/main.js:10:6636313)
    at Layer.handle [as handle_request] (dist/server/us/main.js:10:4081161)
```

When I `console.log(newrelic)`, I have the following object:
```js
{
  config: {
      // ...
  }
}
```

## Expected Behavior

setTransactionName **is** a function and works as expected.

## [Troubleshooting](https://discuss.newrelic.com/t/troubleshooting-frameworks/108787) or [NR Diag](https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/troubleshooting/new-relic-diagnostics) results

[NOTE]: # ( Provide any other relevant log data. )
[TIP]:  # ( Scrub logs and diagnostic information for sensitive information )

## Your Environment

* ex: Node version: v10.16.0
* ex: Operating System and version: macOS High Sierra 10.13.6

## Additional context

Looks the same issue as https://discuss.newrelic.com/t/requiring-newrelic-a-second-time-doesnt-return-an-instance-of-the-api-class/80527

But the discussed solutions doesn't work for me

Changing import to `import * as newrelic from 'newrelic/index';` and `import newrelic from 'newrelic/index';` make build fails with errors 
```
ERROR in ./node_modules/@newrelic/native-metrics/lib/pre-build.js
Module not found: Error: Can't resolve '../package' in '/Users/guillaume.lodi/vc-workspace/ngx-web/node_modules/@newrelic/native-metrics/lib'

ERROR in ./node_modules/node-gyp/lib/node-gyp.js
Module not found: Error: Can't resolve '../package' in '/Users/guillaume.lodi/vc-workspace/ngx-web/node_modules/node-gyp/lib'

ERROR in ./node_modules/@newrelic/native-metrics/lib/pre-build.js
Module not found: Error: Can't resolve 'aws-sdk' in '/Users/guillaume.lodi/vc-workspace/ngx-web/node_modules/@newrelic/native-metrics/lib'
```

Using require `const newrelic = require('newrelic');` doesn't work either.

**Comment by astormnewrelic** [comment] 2020-09-08 18:13
Hi @doliG, nice to meet you.  This sounds like both a typescript configuration issue _and_ possibly a webpack issue.  I'm going to describe what I see and ask you a few questions in the hopes of getting to the bottom of this. 

It looks like we have two issues here -- both come down to how angular is compiling your typescript and javascript code.  

First -- it sounds like something in your or angular's TypeScript compiler chain is trying to resolve NodeJS modules for you and incorrectly loading the New Relic `newrelic.js` configuration file instead of the `newrelic` module in `node_modules`

**We couldn't reproduce this specific error when we ran through the angular universal tutorial**.  Do you, by chance, have the NestJS CLI installed (or have a basic example where  we could reproduce the problem?)  We've seen this "resolves to the configuration file instead of the agent" problem before with NestJS and have [an issue opened with them](https://github.com/nestjs/nest-cli/issues/838) to fix it. 

Also, it sounds like using the `import * as newrelic from 'newrelic/index';` work around solved the "loads `newrelic.js` file instead of the agent" problem, but left you with another one. 

The second problem are these errors

    ERROR in ./node_modules/@newrelic/native-metrics/lib/pre-build.js
    Module not found: Error: Can't resolve '../package' in '/Users/guillaume.lodi/vc-workspace/ngx-web/node_modules/@newrelic/native-metrics/lib'

    ERROR in ./node_modules/node-gyp/lib/node-gyp.js
    Module not found: Error: Can't resolve '../package' in '/Users/guillaume.lodi/vc-workspace/ngx-web/node_modules/node-gyp/lib'

    ERROR in ./node_modules/@newrelic/native-metrics/lib/pre-build.js
    Module not found: Error: Can't resolve 'aws-sdk' in '/Users/guillaume.lodi/vc-workspace/ngx-web/node_modules/@newrelic/native-metrics/lib'

Do you happen to know if Angular Universal uses webpack under the hood?  We're asking because these errors look a lot like errors we've seen where webpack tries to compile your entire `node_modules` folders for a server side application, including some Node Utility scripts.   We usually recommend folks give the [webpack-node-externals](https://github.com/angular/universal/issues/1125) module a try to work around these sorts of issues.  We even have [an experimental webpack plugin](https://www.npmjs.com/package/@newrelic/webpack-plugin) that wraps `webpack-node-externals` for you.  

If you can get us answers to those questions we'll be better able to better tell what's going on.

**Comment by doliG** [comment] 2020-09-09 13:17
Hy @astormnewrelic ,

Thanks a lot for your answer 🙏 

>  Do you, by chance, have the NestJS CLI installed (or have a basic example where we could reproduce the problem?)

We don't, we use an express server.

> Also, it sounds like using the import * as newrelic from 'newrelic/index'; work around solved the "loads newrelic.js file instead of the agent" problem, but left you with another one.

100% agree, it looks like we are finally importing the right file from node_modules, but it leads us to transpiration errors.

Angular **do use webpack** under the hood. I've tested your experimental webpack plugin and here's what happens:

According to [@angular-builders/custom-webpack](https://www.npmjs.com/package/@angular-builders/custom-webpack#custom-webpack-server) doc, I've updated my angular.json like this:

```js
// angular.json
   "server":{
      "builder":"@angular-builders/custom-webpack:server",
      "options":{
         "customWebpackConfig":{
            "path":"./extra-webpack-server.config.js",
            "mergeStrategies":{
               "module.rules":"append"
            },
            "replaceDuplicatePlugins":true,
            // ...
         }
      }
   }

```

Then according to [@newrelic/webpack-plugin](https://www.npmjs.com/package/@newrelic/webpack-plugin) I've added the following file in my repo:

```js
// extra-webpack-server.config.js
const nodeExternals = require('@newrelic/webpack-plugin/lib/externals')
const NewrelicWebpackPlugin = require('@newrelic/webpack-plugin/lib/NewrelicWebpackPlugin')

module.exports = {
  /* ... */
  externals: [nodeExternals()],
  plugins: [
    new NewrelicWebpackPlugin()
  ]
  /* ... */
}
```


After a build, when running my server, I have the following error:
```
node_modules/instantsearch.js/es/index.js:2
import algoliasearchHelper from 'algoliasearch-helper';
       ^^^^^^^^^^^^^^^^^^^

SyntaxError: Unexpected identifier
    at Module._compile (internal/modules/cjs/loader.js:721:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module._load (node_modules/sqreen/lib/instrumentation/moduleHijacker.js:70:35)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at _c0 (node_modules/angular-instantsearch/bundles/angular-instantsearch.umd.js:2:222)
    at Object.<anonymous> (node_modules/angular-instantsearch/bundles/angular-instantsearch.umd.js:5:2)
```

It is as if my TS files was not loaded correctly anymore. No idea why though... Maybe Angular config is not correctly applied ? 🤔 
What do you think ?

**Comment by astormnewrelic** [comment] 2020-09-09 17:08
@doliG  Well, we're learning a lot about angular's build process this week. :)

I'm going to let you know what I see, and then talk about some possible next things for you to try. 

>  What do you think ?

The way `webpack-node-externals` works is it assumes you _only_ want to compile your project code, and that you don't want to compile code from `node_modules` that your project accesses.  The working theory is a lot of the Node.js specific code you find on NPM (like the New Relic agent) isn't built to work with Webpack since webpack has a strong bias towards compiling/transpiling code meant for the browser.  With `webpack-node-externals` you skip compiling these modules, and then deploy your compiled server application along side the `node_modules` folder.

So, with that framng -- when you said

> It is as if my TS files was not loaded correctly anymore

I don't see that. If I look at your error, I don't see errors from any of _your_ TypeScript files.  Instead I see a problem with a file from the `instantsearch.js` module/package. If I look at the code `instantsearch.js` is distributing.

    % cat node_modules/instantsearch.js/es/index.js
    import InstantSearch from './lib/InstantSearch';
    // ...
    
This isn't TypeScript -- it's a regular javascript file that's using ES6 import statements. My guess is it's intended to be built into a single javascript file with a tool like webpack or babel -- (that's typically how ES6 import statements work in javascript)

So -- it looks Angular needs to build this file for -- reasons? -- and in general that Angular might need/want to build things from your `node_modules` folder.  This runs counter to how the `webpack-node-externals` functionality works out of the box.

Next Steps:

I see three possible paths to continue on.

1. The `nodeExternals` function from `webpack-node-externals` has functionality that will allow you to say "hey, I _do_ want files from this `node_modules` package compiled.  You can read about this functionality here: https://github.com/liady/webpack-node-externals#how-can-i-bundle-required-assets-ie-css-files-from-node_modules   Having your webpack config  listing the modules you need to compile is one approach to try

2. It would be a long slog, but we're very open to PRs to our various projects that would make them compilable via webpack and remove the warnings you're see.

3. You mentioned earlier that `require('newrelic')` didn't work for you.  We could revisit this -- specifically, I'm wondering what sort of object `require('newrelic')` returns for you, and if doing `require('newrelic/index')` instead might be a temporary workaround for your situation?

**Comment by dulikmixail** [comment] 2021-04-05 06:59
Hello, 
I'm getting the same error for for Angular 11 with Universal. Is there currently a solution that would accurately fix the current error without using the `nodeExternals` function from `webpack-node-externals`?

**Comment by carlo-808** [comment] 2021-04-05 16:02
Hello @dulikmixail , we don't really have a better solution than using `nodeExternals` and `webpack-node-externals`. It sounds like you are having issues with that solution?

**Comment by dulikmixail** [comment] 2021-04-05 16:57
@carlo-808 No, solutions with `nodeExternals` and `webpack-node-externals` work for me.

**Comment by michaelgoin** [comment] 2021-07-08 21:41
Closing this as it falls under a general webpack support. Currently, we don't have plans to add better support for webpack (but that is subject to change as tracked as a part of webpack feature requests).

**Closed by michaelgoin** 2021-07-08 21:41 UTC
Labels: bug, webpack, will not fix
