### ISSUE TITLE
v11.x.y does not work well with Pino

### ISSUE THREAD

**Issue by y-a-v-a** [newrelic/node-newrelic#1802] opened 2023-10-09 11:50 UTC
## Description

In a NextJS 12.3.4 application we have a custom server along with Pino and NewRelic.

```json
{
  "@newrelic/next": "0.5.2",
  "@types/newrelic": "9.14.0",
  "newrelic": "11.1.0",
  "pino": "8.15.7",
  "pino-pretty": "10.2.3",
  "next": "12.3.4"
}
```
When I start up Next with the following command, the application starts throwing errors immediately, but nothing to `stdout` or `stderr`.

```shell
NEW_RELIC_APP_NAME="DEV Storefront" NEW_RELIC_NO_CONFIG_FILE=true NEW_RELIC_ENABLED=true NEW_RELIC_LICENSE_KEY=123abc NODE_OPTIONS="--experimental-loader newrelic/esm-loader.mjs -r @newrelic/next --inspect" node ./server.js
```

From the inspector panel I do see the following:

![Screenshot 2023-10-09 at 12 26 26](https://github.com/newrelic/node-newrelic/assets/375507/0bad5241-69bf-4071-acff-c990cd45a04e)

From one.newrelic.com we see continuous errors reported

```
                                                      at ThreadStream.write (/usr/src/app/storefront/node_modules/thread-stream/index.js:232:19)
                                                                  at Pino.write (/usr/src/app/storefront/node_modules/pino/lib/proto.js:215:10)
                                                          at Pino.LOG [as error] (/usr/src/app/storefront/node_modules/pino/lib/tools.js:62:21)
                                                                              at process.<anonymous> (/usr/src/app/storefront/server.js:101:12)
                                                                                                          /at process.emit (node:events:526:35)
                    at process.wrappedEmit [as emit] (/usr/src/app/storefront/node_modules/newrelic/lib/instrumentation/core/globals.js:54:23)
                                                                                at process.<anonymous> (node:internal/process/execution:149:25)
at process.wrappedFatalException [as _fatalException] (/usr/src/app/storefront/node_modules/newrelic/lib/instrumentation/core/globals.js:33:23)

```

## Expected Behavior

No errors are reported, output is sent to stdout.

## [Troubleshooting](https://discuss.newrelic.com/t/troubleshooting-frameworks/108787) or [NR Diag](https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/troubleshooting/new-relic-diagnostics) results

[NOTE]: # ( Provide any other relevant log data. )
[TIP]:  # ( Scrub logs and diagnostic information for sensitive information )

## Steps to Reproduce

[NOTE]: # ( Please be as specific as possible. )
[TIP]:  # ( Link a sample application that demonstrates the issue. )

## Your Environment

NextJS v12.3.4 runs in a Docker container, versions of deps as mentioned above.
Also reproducible on Mac OS 13.5.2
NodeJS 18.17.1

All works as expected when using NewRelic v10.x.x (up until its latest version).

## Additional context

Similar report found here: https://forum.newrelic.com/s/hubtopic/aAX8W000000PHYsWAO/newrelic-does-not-show-logs-for-nextjs-app?t=1696848988884

Upgrading `@newrelic/next` doesn't make a difference. Dropping `pino-pretty` in favor of using `pino/file` doesn't make a difference either.

**Comment by bizob2828** [comment] 2023-10-09 12:23
Hi @y-a-v-a sorry for your troubles. Can you provide a more concrete reproduction case?

**Comment by y-a-v-a** [comment] 2023-10-09 14:03
Example repo here:
https://github.com/y-a-v-a/newrelic-pino
branch `main` errors
branch `no-pino` works like a charm ;-)

Cheers,
Vincent

**Comment by bizob2828** [comment] 2023-10-09 16:27
Hi @y-a-v-a this is a duplicate of #1777.  It's a bug in a 3rd party package we use to instrument ESM(`import-in-the-middle`).  I'll close this as a duplicate

**Closed by bizob2828** 2023-10-09 16:27 UTC
Labels: bug, needs-triage
