### ISSUE TITLE
Memory Leak Warning

### ISSUE THREAD

**Issue by zxlin** [newrelic/node-newrelic#299] opened 2019-09-04 00:54 UTC
I recently started getting a possible memory leak warning. 

```
MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 stopped listeners added. Use emitter.setMaxListeners() to increase limit
    at _addListener (events.js:256:17)
    at Agent.addListener (events.js:272:10)
    at Agent.once (events.js:301:8)
    at Object.request (/home/usr/project/node_modules/newrelic/lib/utilization/common.js:95:9)
    at Object.fetchAzureInfo [as azure] (/home/usr/project/node_modules/newrelic/lib/utilization/azure-info.js:27:10)
    at getVendorInfo (/home/usr/project/node_modules/newrelic/lib/utilization/index.js:20:27)
    at Array.forEach (<anonymous>)
    at Object.getVendors (/home/usr/project/node_modules/newrelic/lib/utilization/index.js:19:16)
    at fetchSystemInfo (/home/usr/project/node_modules/newrelic/lib/system-info.js:93:15)
    at /home/usr/project/node_modules/newrelic/node_modules/async/dist/async.js:66:19
    at /home/usr/project/node_modules/newrelic/node_modules/async/dist/async.js:3880:24
    at replenish (/home/usr/project/node_modules/newrelic/node_modules/async/dist/async.js:1011:17)
    at /home/usr/project/node_modules/newrelic/node_modules/async/dist/async.js:1016:9
    at eachOfLimit (/home/usr/project/node_modules/newrelic/node_modules/async/dist/async.js:1041:24)
    at /home/usr/project/node_modules/newrelic/node_modules/async/dist/async.js:1046:16
```

This was observed when the http server had no activity against it (no requests came in around the time this warning popped)

node: `v10.16.2`
newrelic: `v5.11.0`

Below is some additional information about the event emitter in question, do you guys know what may be causing this?

```
  emitter:
   Agent {
     domain: null,
     _events:
      [Object: null prototype] {
        transactionFinished: [Function: bound _transactionFinished],
        unload: [Array],
        errored: [Array],
        stopped: [Array] },
     _eventsCount: 4,
     _maxListeners: undefined,
     _state: 'connecting',
     config: [redacted]
     environment:
      { setFramework: [Function: setFramework],
        setDispatcher: [Function: setDispatcher],
        clearFramework: [Function: clearFramework],
        clearDispatcher: [Function: clearDispatcher],
        listPackages: [Function: listPackages],
        getJSON: [Function: getJSON],
        get: [Function: getSetting],
        refresh: [Function: refresh] },
     version: '5.11.0',
     collector:
      CollectorAPI { _agent: [Circular], _reqHeadersMap: null, _methods: [Object] },
     events:
      PriorityQueue { limit: 10000, seen: 0, _data: [FibonacciHeap] },
     customEvents:
      PriorityQueue { limit: 1000, seen: 0, _data: [FibonacciHeap] },
     errors:
      ErrorAggregator {
        _events: [PriorityQueue],
        config: [Config],
        errorCount: 0,
        webTransactionErrorCount: 0,
        otherTransactionErrorCount: 0,
        expectedErrorCount: 0,
        expectedWebTransactionErrorCount: 0,
        expectedOtherTransactionErrorCount: 0,
        errors: [],
        seenObjectsByTransaction: [Object: null prototype] {},
        seenStringsByTransaction: [Object: null prototype] {} },
     mapper:
      MetricMapper {
        unscoped: [Object: null prototype] {},
        scoped: [Object: null prototype] {},
        length: 0 },
     metricNameNormalizer:
      MetricNormalizer {
        domain: null,
        _events: [Object: null prototype] {},
        _eventsCount: 0,
        _maxListeners: undefined,
        config: [Config],
        type: 'metric name',
        formatter: [Function: plain],
        rules: [] },
     metrics:
      Metrics {
        empty: false,
        started: 1567483113638,
        apdexT: 0.1,
        mapper: [MetricMapper],
        normalizer: [MetricNormalizer],
        unscoped: [Object],
        scoped: [Object: null prototype] {} },
     spans: SpanAggregator { _events: [PriorityQueue] },
     transactionNameNormalizer:
      MetricNormalizer {
        domain: null,
        _events: [Object: null prototype] {},
        _eventsCount: 0,
        _maxListeners: undefined,
        config: [Config],
        type: 'transaction name',
        formatter: [Function: plain],
        rules: [] },
     txSegmentNormalizer: TxSegmentNormalizer { terms: [] },
     urlNormalizer:
      MetricNormalizer {
        domain: null,
        _events: [Object: null prototype] {},
        _eventsCount: 0,
        _maxListeners: undefined,
        config: [Config],
        type: 'URL',
        formatter: [Function: url],
        rules: [Array] },
     userNormalizer:
      MetricNormalizer {
        domain: null,
        _events: [Object: null prototype] {},
        _eventsCount: 0,
        _maxListeners: undefined,
        config: [Config],
        type: 'user',
        formatter: [Function: plain],
        rules: [Array] },
     tracer: Tracer { agent: [Circular], _segment: null },
     traces:
      TraceAggregator {
        reported: 0,
        config: [Config],
        capacity: 20,
        trace: null,
        syntheticsTraces: [],
        requestTimes: [Object: null prototype] {},
        noTraceSubmitted: 0 },
     transactionSampler:
      AdaptiveSampler {
        _serverless: false,
        _seen: 0,
        _sampled: 0,
        _samplingPeriod: 60000,
        _samplingTarget: 10,
        _maxSamples: 20,
        _samplingThreshold: 0,
        _resetCount: 4329,
        _resetInterval:
         Timeout {
           _called: true,
           _idleTimeout: 60000,
           _idlePrev: null,
           _idleNext: null,
           _idleStart: 303,
           _onTimeout: [Function],
           _timerArgs: undefined,
           _repeat: 60000,
           _destroyed: false,
           _handle: [Timer],
           [Symbol(unrefed)]: false,
           [Symbol(asyncId)]: 9,
           [Symbol(triggerId)]: 1 } },
     queries: QueryTracer { samples: Map {}, config: [Config] },
     totalActiveSegments: 0,
     segmentsCreatedInHarvest: 0,
     segmentsClearedInHarvest: 0,
     activeTransactions: 0,
     transactionsCreatedInHarvest: 0,
     harvesterHandle:
      Timeout {
        _called: true,
        _idleTimeout: -1,
        _idlePrev: null,
        _idleNext: null,
        _idleStart: 259703211,
        _onTimeout: null,
        _timerArgs: undefined,
        _repeat: null,
        _destroyed: true,
        _handle: [Timer],
        [Symbol(unrefed)]: false,
        [Symbol(asyncId)]: 905620,
        [Symbol(triggerId)]: 905617 },
     _lastHarvest:
      Harvest { agent: [Circular], startTime: 1567483113638, _steps: [Object] },
     transactionCreatedInHarvest: Na
```

**Comment by michaelgoin** [comment] 2019-09-04 17:19
Hi @zxlin,

Thanks for bringing this to our attention.

We'd expect at most to have like 3 in play for the 'stopped' event at any given time as we attempt to grab environment data for certain cloud providers. 

Scanning the code, I see where maybe we could have one issue.

If you look at your logs, do you see anything indicating one or more restarts for the agent without any shutdowns / app restarts? I think in certain cases we may not cleanup the event subscription and then create new ones when just the agent restarts.

Thanks!

Michael

**Comment by zxlin** [comment] 2019-09-04 17:45
@michaelgoin To be quite honest, I'm not certain of the exact timestamp when this occurred, but going off of a highly educated guess, these are some of the logs around the time this may have occurred. 

Are these the agent restart events that you're looking for? 

For context, this particular app did not restart/shutdown between 2019-08-31 and 2019-09-04 (time of posting). This app is also running in a dev environment on a self-hosted server (not in a cloud provider) since you mentioned it may be grabbing env data of the cloud provider. 


```
{"v":0,"level":30,"name":"newrelic","hostname":"ubuntu","pid":3071,"time":"2019-09-03T03:58:33.537Z","msg":"Harvest started."}
{"v":0,"level":30,"name":"newrelic","hostname":"ubuntu","pid":3077,"time":"2019-09-03T03:58:33.638Z","msg":"Harvest started."}
{"v":0,"level":50,"name":"newrelic","hostname":"ubuntu","pid":3071,"time":"2019-09-03T03:58:33.655Z","msg":"Agent endpoint metric_data returned 409 status. Restarting.","component":"collector_api"}
{"v":0,"level":30,"name":"newrelic","hostname":"ubuntu","pid":3071,"time":"2019-09-03T03:58:33.655Z","msg":"Restart requested. Harvest will complete upon restart finish."}
{"v":0,"level":30,"name":"newrelic","hostname":"ubuntu","pid":3071,"time":"2019-09-03T03:58:33.655Z","msg":"Restarting collector.","component":"collector_api"}
{"v":0,"level":30,"name":"newrelic","hostname":"ubuntu","pid":3071,"time":"2019-09-03T03:58:33.655Z","msg":"Shutting down collector.","component":"collector_api"}
{"v":0,"level":50,"name":"newrelic","hostname":"ubuntu","pid":3077,"time":"2019-09-03T03:58:33.732Z","msg":"Agent endpoint metric_data returned 409 status. Restarting.","component":"collector_api"}
{"v":0,"level":30,"name":"newrelic","hostname":"ubuntu","pid":3077,"time":"2019-09-03T03:58:33.732Z","msg":"Restart requested. Harvest will complete upon restart finish."}
{"v":0,"level":30,"name":"newrelic","hostname":"ubuntu","pid":3077,"time":"2019-09-03T03:58:33.732Z","msg":"Restarting collector.","component":"collector_api"}
{"v":0,"level":30,"name":"newrelic","hostname":"ubuntu","pid":3077,"time":"2019-09-03T03:58:33.732Z","msg":"Shutting down collector.","component":"collector_api"}
{"v":0,"level":30,"name":"newrelic","hostname":"ubuntu","pid":3071,"time":"2019-09-03T03:58:33.742Z","msg":"Agent state changed from connected to disconnected."}
{"v":0,"level":30,"name":"newrelic","hostname":"ubuntu","pid":3071,"time":"2019-09-03T03:58:33.742Z","msg":"Disconnected from New Relic; clearing run ID [redacted].","component":"collector_api"}
{"v":0,"level":30,"name":"newrelic","hostname":"ubuntu","pid":3071,"time":"2019-09-03T03:58:33.742Z","msg":"Agent state changed from disconnected to connecting."}
{"v":0,"level":30,"name":"newrelic","hostname":"ubuntu","pid":3077,"time":"2019-09-03T03:58:33.826Z","msg":"Agent state changed from connected to disconnected."}
{"v":0,"level":30,"name":"newrelic","hostname":"ubuntu","pid":3077,"time":"2019-09-03T03:58:33.826Z","msg":"Disconnected from New Relic; clearing run ID [redacted].","component":"collector_api"}
{"v":0,"level":30,"name":"newrelic","hostname":"ubuntu","pid":3077,"time":"2019-09-03T03:58:33.826Z","msg":"Agent state changed from disconnected to connecting."}
{"v":0,"level":30,"name":"newrelic","hostname":"ubuntu","pid":3077,"time":"2019-09-03T03:58:35.147Z","msg":"Agent state changed from connecting to connected."}
{"v":0,"level":30,"name":"newrelic","hostname":"ubuntu","pid":3071,"time":"2019-09-03T03:58:35.148Z","msg":"Agent state changed from connecting to connected."}
{"v":0,"level":30,"name":"newrelic","hostname":"ubuntu","pid":3077,"time":"2019-09-03T03:58:35.147Z","msg":"Connected to collector-010.newrelic.com:443 with agent run ID [redacted].","component":"collector_api"}
{"v":0,"level":30,"name":"newrelic","hostname":"ubuntu","pid":3077,"time":"2019-09-03T03:58:35.148Z","msg":"Reporting to: https://rpm.newrelic.com/accounts/[redacted]/applications/[redacted]","component":"collector_api"}
{"v":0,"level":30,"name":"newrelic","hostname":"ubuntu","pid":3077,"time":"2019-09-03T03:58:35.150Z","msg":"Harvest finished."}
{"v":0,"level":30,"name":"newrelic","hostname":"ubuntu","pid":3071,"time":"2019-09-03T03:58:35.148Z","msg":"Connected to collector-010.newrelic.com:443 with agent run ID [redacted].","component":"collector_api"}
{"v":0,"level":30,"name":"newrelic","hostname":"ubuntu","pid":3071,"time":"2019-09-03T03:58:35.148Z","msg":"Reporting to: https://rpm.newrelic.com/accounts/[redacted]/applications/[redacted]","component":"collector_api"}
{"v":0,"level":30,"name":"newrelic","hostname":"ubuntu","pid":3071,"time":"2019-09-03T03:58:35.151Z","msg":"Harvest finished."}
{"v":0,"level":30,"name":"newrelic","hostname":"ubuntu","pid":3071,"time":"2019-09-03T03:59:33.540Z","msg":"Harvest started."}
```

**Comment by michaelgoin** [comment] 2019-09-04 17:49
@zxlin perfect, that is in fact a restart. i wouldn't expect just one to trigger the issue but definitely gives me more confidence in the theory.

Also, not being on a cloud provider is what I would expect to contribute to the case. We sort of do a check to see if we are running in such on environment upon each startup. That's when I'd one of those two error cases to occur.

I've entered a bug locally and we'll try to get a fix in before too long on what I think is the cause.

Thanks!

**Comment by zxlin** [comment] 2019-09-04 18:51
@michaelgoin yeah, our monitoring infrastructure sees the requests to the instance metadata services. I have only observed this occurring twice, specifically this only started after an upgrade to `v5.11.0` of this package. If that helps at all :) 

Thanks for looking into this so quickly.

**Comment by DullReferenceException** [comment] 2019-09-07 00:05
We might be encountering the same issue, in `5.2.0`. Haven't checked yet to see if an upgrade changes things. In our case, we're doing `proc.once('message', ...)` on a child process object:

```
(node:1) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 message listeners added. Use emitter.setMaxListeners() to increase limit
    at _addListener (events.js:243:17)
    at ChildProcess.addListener (events.js:259:10)
    at ChildProcess.wrappedChildProcessOn [as on] (/src/node_modules/newrelic/lib/instrumentation/core/child_process.js:38:21)
    at ChildProcess.once (events.js:290:8)
    at /our/code.js
    ...
```

Based on our logs, we shouldn't be encountering any conditions where the `once` handler isn't being invoked. Is `newrelic` perhaps not cleaning up after `.once` listeners? I see `.once` was used in @zxlin's case as well.

**Comment by DullReferenceException** [comment] 2019-09-07 00:09
Oh, and in our case, this is happening very shortly after startup, so it's not likely due to agent restarts. It's most likely happening after a single occurrence of attaching the event listener.

**Comment by DullReferenceException** [comment] 2019-09-07 00:19
Possibly related, we do run newrelic agents inside a pool of _child processes_, but those should be isolated from each other, I'd imagine.

**Comment by zxlin** [comment] 2019-09-11 17:55
@michaelgoin I want to also report that this is now also occurring on an AWS environment as well. Same restart message in the agent log without actual restarts to the app itself.

**Comment by carlonewrelic** [comment] 2019-10-17 21:46
Hi @zxlin ,

In newrelic-node version 5.13.1, we added a fix for the memory leak warning around too many event listeners.  Please give it a try and let us know if your issue was resolved.  I'm closing out this issue but feel free to reopen/comment if you are still seeing the warning.  Thanks!

**Closed by carlonewrelic** 2019-10-17 21:46 UTC

**Comment by Arthur-xu** [comment] 2023-12-28 02:13
HI @carlo-808 I still hit this warning 
`MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 uncaughtException listeners added to [process]. Use emitter.setMaxListeners() to increase limit`

Agent version: 11.7.0; Node version: v18.19.0."
