### ISSUE TITLE
if an error is thrown in `newrelic.js`, the error is swollen 

### ISSUE THREAD

**Issue by mohsen1** [newrelic/node-newrelic#291] opened 2019-07-29 17:40 UTC
make a simple `newrelic.js` with following contents:

```js
throw new Error('Error from "newrelic.js')
```

now run `node -e "require('newrelic')"`

Resulting output **does not** include the actual error.

```
New Relic for Node.js is disabled due to an error:
....
```

**Comment by astormnewrelic** [comment] 2019-08-05 18:21
Mohsen,

Nice to meet you, and thanks for saying hello!

The behavior you describe is the intended behavior.  When the agent encounters an error loading the configuration, we catch that error and raise/throw a new error with a more useful warning _for less experienced folks_ trying to get the agent installed.  

For more advanced users (like yourself) we also [log the original error](https://github.com/newrelic/node-newrelic/blob/master/lib/config/index.js#L1511) before re-throwing.

Since this is intended behavior we're going to close this issue out.  However, if you need more help or we've misunderstood your request, please feel free to reopen the issue and/or keep the conversation going.  Also, if you need _Official Support™_, the fastest way to resolve any issue with the Node Agent is via our standard support channels -- if this is one of those issues you can get started with that over at [https://support.newrelic.com/](https://support.newrelic.com/).

**Closed by astormnewrelic** 2019-08-05 18:21 UTC
