### ISSUE TITLE
ESM loader in v11 does not work with @apollo/server package

### ISSUE THREAD

**Issue by barryhagan** [newrelic/node-newrelic#1777] opened 2023-09-02 03:02 UTC
## Description

Attempting to use v11 in an ESM project that includes @apollo/server causes the node process to crash.

In Node v18 you will get a silent exit code 13.  In Node v20, it will throw a SyntaxError before exit code 1.

## Expected Behavior

Running `node --loader newrelic/esm-loader.mjs` should work without crashing node.

## Steps to Reproduce

Repro is here using `import-in-the-middle` directly: https://github.com/barryhagan/iitm-apollo-server-repro

You will get the same behavior if you use `newrelic/esm-loader.mjs` since that is just a re-export of iitm

## Your Environment

ESM project
node 18.17.1
newrelic 11.0.0

## Additional context

I've opened this issue for import-in-the-middle: https://github.com/DataDog/import-in-the-middle/issues/31

TBD if they can/will fix this or blame @apollo/server

**Comment by bizob2828** [comment] 2023-09-11 12:53
@barryhagan sorry for your troubles.  I'll dig into the import-in-the-middle code and see if I can provide a fix for it.

**Comment by bizob2828** [comment] 2023-09-11 17:55
I'm going to keep this open even though the fix needs to be made in `import-in-the-middle`

**Comment by bizob2828** [comment] 2023-09-12 20:17
It's worth noting this problem only exists on Node 20.  Workarounds are use Node 16, or 18.  Lastly, thhe loader is still experimental from Node.js runtime which in turns means our support is experimental.  A fix for this may be within a semver patch/minor.

**Comment by barryhagan** [comment] 2023-09-12 21:12
I am trying to use this with Node18, and that causes exit code 13.   We will remain on version 10 of newrelic for now since that works.

**Comment by bizob2828** [comment] 2023-09-12 21:18
The exit code 13 is expected because the loaders CLI flag from Node.js is still experimental.

**Comment by barryhagan** [comment] 2023-09-13 01:50
Maybe I wasn't clear enough.  In a Node18 environment with an ESM project that imports @apollo/server as a dependency, you cannot use the loader from v11 of newrelic.  It causes the process to terminate unexpectedly before _any_  code is run.   All you get is an exit code 13 from Node.  It silently exits even if the first line of code is a console.log statement as shown in this [repro](https://github.com/barryhagan/iitm-apollo-server-repro)

My only choice is to stay on v10 of newrelic right now.

I am mainly surfacing this incompatibility between import-in-the-middle and @apollo/server so others don't have to waste as much time as I did to find out which dependency was the issue or what to look for if upgrading to v11 suddenly causes your project to exit before doing anything. I imagine this is not the only package that causes iitm to fail, as is shown in the trivial example [here](https://github.com/DataDog/dd-trace-js/issues/3595).

I opened this issue to track https://github.com/DataDog/import-in-the-middle/issues/31 so you can bump your dependency when/if that gets fixed.  Until then I will patiently wait in v10.

**Comment by bizob2828** [comment] 2023-09-13 14:26
Ah you're right.  So in Node 20 the issue is https://github.com/DataDog/import-in-the-middle/issues/31.  Even if this gets fixed, it'll still be broken because of https://github.com/DataDog/dd-trace-js/issues/3595. Although that's logged to the Datadog agent, it's actually a problem with import in the middle

**Comment by bizob2828** [comment] 2023-09-13 14:50
There's no work on the agent. We have to wait for `import-in-the-middle` to release fixes.  I offered up help but the maintainers are a little busy atm

**Comment by jsumners-nr** [comment] 2023-12-07 15:23
We have a potential solution added in https://github.com/DataDog/import-in-the-middle/pull/43. 🤞 it is acceptable to upstream.

**Comment by bizob2828** [comment] 2023-12-15 17:02
@barryhagan the [PR](https://github.com/DataDog/import-in-the-middle/pull/43) was released as 1.7.2 of `import-in-the-middle`. I upgraded to the latest and re-ran your repro and it does not crash. I'm closing this issue

**Closed by bizob2828** 2023-12-15 17:02 UTC
Labels: bug

**Comment by barryhagan** [comment] 2023-12-15 18:50
>I opened this issue to track https://github.com/DataDog/import-in-the-middle/issues/31 so you can bump your dependency when/if that gets fixed.

So, bump your dependency?

**Comment by bizob2828** [comment] 2023-12-15 19:03
@barryhagan we don't bundle dependencies. If you just do a fresh install of the agent, it'll pick up the 1.7.2 version of import-in-the-middle
