### ISSUE TITLE
Newrelic node agent not working with Next JS 13.4+ app router version

### ISSUE THREAD

**Issue by maneetlodha2839** [newrelic/node-newrelic#1794] opened 2023-10-04 11:17 UTC
Getting this error:
 Return statement is not allowed here
 
 22 │ const pkgJSON = require('./package.json')
 23 │ if (!isMainThread) {
 24 │   logger.warn('Using New Relic for Node.js in worker_threads is not supported. Not starting!')
 25 │   return
    ·   ──────
 26 │ }

## Description

I am using the Next JS 13.5 with app router and when trying to implement newrelic for browser using the node agent then getting the above error

## Steps to Reproduce

1. Create a new next js 13.4 project.
2. Use app router config, and in root layout file try importing the newrelic package. 
3. Add this code before return:
  const browserTimingHeader = newrelic.getBrowserTimingHeader({
    hasToRemoveScriptWrapper: true,
  });

Now you will get the error, probably you will get just by importing the newrelic module

@newrelic/next: ^0.7.0
newrelic: ^11.1.0,
react: "18.2.0",
next: "^13.5",
Node version: 18.12

**Comment by bizob2828** [comment] 2023-10-04 15:16
This is a duplicate of #1783

**Closed by bizob2828** 2023-10-04 15:16 UTC
Labels: bug, needs-triage
