### ISSUE TITLE
UncaughtException: socket.destroy is not a function

### ISSUE THREAD

**Issue by xjme** [newrelic/node-newrelic#308] opened 2019-10-21 12:01 UTC
Since the last update (5.13.1), we randomly encaunter following error, which causes application to crash.

`uncaughtException: socket.destroy is not a function`, which is invoked by freeSocket function within `newrelic/node_modules/agent-base/index.js:169:10`. Dependancy on agent-base module is new, it was not there before the update.

We use v10.16.3 of nodejs. Could you please elaborate the problem?

**Comment by astormnewrelic** [comment] 2019-10-21 15:07
Thanks for letting us know @xjme -- we haven't heard reports of this issue yet. If you're looking for immediate support the fastest way to get the right eyes on this issue will be submitting it via official support channels.  https://support.newrelic.com/ -- that said we're always happy to be an extra set of eyes on an issue, especially if it helps us improve the agent. 

The `agent-base` module is a dependency of the [`https-proxy-agent` module](https://www.npmjs.com/package/https-proxy-agent), which we use for providing proxy server support. This module recently required an upgrade. It sounds like somehow the `freeSocket` method is being passed something that's not a socket. You might have luck reporting this to the upstream provider.

Also, if you can provide a full callstack or reproduction we might be able to help you figure out what's going on.

**Comment by nimadera** [comment] 2019-10-21 15:28
Looks like [this error](https://github.com/TooTallNate/node-https-proxy-agent/pull/83) is resolved in the [latest patch release](https://github.com/TooTallNate/node-https-proxy-agent/releases/tag/3.0.1) of the `https-proxy-agent` module.

**Comment by astormnewrelic** [comment] 2019-10-21 15:34
Thank you @nimadera!

@xjme It sounds like this issue's been fixed by the upstream provider.  Since the Node Agent has a SemVer dependency of `"https-proxy-agent": "^3.0.0",`, this means the next time you do an `npm update` or a fresh `npm install` you should get the latest `https-proxy-agent` and should get this fix.  

We're going to close this issue out for now, but if the latest `http-proxy-agent` doesn't fix your issue please feel free to reopen/open-a-new-issue.

**Closed by astormnewrelic** 2019-10-21 15:34 UTC
