### ISSUE TITLE
Error with agent version 9.12.1 and aws-sdk version 3.266.1

### ISSUE THREAD

**Issue by atodd** [newrelic/node-newrelic#1549] opened 2023-03-17 16:37 UTC
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

The latest release of this agent is causing issues with aws-sdk:

```
[nuxt] [request error] [unhandled] [500] The request signature we calculated does not match the signature you provided. Check your key and signing method.
  at throwDefaultError (./.output/server/node_modules/@aws-sdk/smithy-client/dist-cjs/default-error-handler.js:8:22)
  at deserializeAws_restXmlGetObjectCommandError (./.output/server/node_modules/@aws-sdk/client-s3/dist-cjs/protocols/Aws_restXml.js:4356:51)
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  at async ./.output/server/node_modules/@aws-sdk/middleware-serde/dist-cjs/deserializerMiddleware.js:7:24
  at async wrappedMiddleware (/usr/local/lib/node_modules/newrelic/node_modules/@newrelic/aws-sdk/lib/v3/smithy-client.js:82:22)
  at async ./.output/server/node_modules/@aws-sdk/middleware-signing/dist-cjs/middleware.js:14:20
  at async ./.output/server/node_modules/@aws-sdk/middleware-retry/dist-cjs/retryMiddleware.js:27:46
  at async ./.output/server/node_modules/@aws-sdk/middleware-flexible-checksums/dist-cjs/flexibleChecksumsMiddleware.js:58:20
  at async wrappedHeaderMw (/usr/local/lib/node_modules/newrelic/node_modules/@newrelic/aws-sdk/lib/v3/smithy-client.js:60:12)
  at async ./.output/server/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:5:22
```

[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT share sensitive information, whether personal, proprietary, or otherwise! )

## Expected Behavior

[NOTE]: # ( Tell us what you expected to happen. )

## [Troubleshooting](https://discuss.newrelic.com/t/troubleshooting-frameworks/108787) or [NR Diag](https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/troubleshooting/new-relic-diagnostics) results

[NOTE]: # ( Provide any other relevant log data. )
[TIP]:  # ( Scrub logs and diagnostic information for sensitive information )

## Steps to Reproduce

[NOTE]: # ( Please be as specific as possible. )
[TIP]:  # ( Link a sample application that demonstrates the issue. )

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )

Node version: 18.12.1
New Relic version: 9.12.1
AWS SDK version: 9.266.1

## Additional context

[TIP]:  # ( Add any other context about the problem here. For example, relevant community posts or support tickets. )

**Comment by bizob2828** [comment] 2023-03-17 16:59
@atodd sorry for the troubles. Do you mind posting a reproduction case please?

**Comment by ahmednaser94** [comment] 2023-03-17 22:09
Our production code broke with same error and after debugging for 2 days when we removed new relic keys from env vars everything worked fine

**Comment by ahmednaser94** [comment] 2023-03-17 22:13
@bizob2828 the steps to reproduce in nodejs 
when we were uploading files it gave this error and it gone away when we removed newrelic key from env vars after trying dozens of solutions to find the bug but after all it was due to newrelic 

![image](https://user-images.githubusercontent.com/39867467/226062086-255865e6-674b-40a5-b968-014149e713a0.png)

**Comment by bizob2828** [comment] 2023-03-17 22:19
Our tests probably didn't catch this because we mock out AWS. In the meantime you can pin newrelic to 9.12.0 until we can triage properly and release a fix.

**Comment by mrickard** [comment] 2023-03-17 23:45
@ahmednaser94 @atodd You'll want to pin your version to 9.11.0. There was a release-pipeline issue with 9.12.0, so the next previous version is 9.11.0.

**Comment by atodd** [comment] 2023-03-20 13:01
@bizob2828 Thank you for the quick response and fix!

**Comment by marcoswca** [comment] 2023-03-23 03:10
I'm using the [serverless-newrelic-lambda-layers](https://github.com/newrelic/serverless-newrelic-lambda-layers) and I'm facing the same problem when I'm trying to get the pre-signed URL to download some file

![Screenshot 2023-03-23 at 00 05 38](https://user-images.githubusercontent.com/9269700/227090792-b9681ab6-cf3f-4fc7-8e8d-dda3b35ed0eb.png)

And this is happening because of this `host;x-new-relic-disable-dt`

![Screenshot 2023-03-23 at 00 06 37](https://user-images.githubusercontent.com/9269700/227090475-87a07543-7957-4312-9d22-337c7aeec12b.png)

Is this related to this thread?

**Comment by mrickard** [comment] 2023-03-23 13:16
@marcoswca The issue you're having is related to this thread. What's the layer ARN your function's using? If it's less than the latest, you can update that in the AWS Lambda console. (Latest layer versions can be found here: https://layers.newrelic-external.com/)

**Comment by marcoswca** [comment] 2023-03-23 14:17
@mrickard This is happening with the latest layer (version 19). I updated to use version 18 and it's working now. Thank you!

**Comment by mrickard** [comment] 2023-03-23 15:52
@marcoswca That's interesting--it's the opposite of what I'd expect. What's the full ARN you're using?

Node 18 version 18 contains 9.12.1, which we're aware has this conflict with AWS SDK. 
Node 18 layer version 19 contains 9.13.0, which shipped a fix for that conflict.
We've also just published a new Node layer version in all regions, which would be version 20 for Node 18. That contains some new features as well as the fix from the previous version.

**Comment by pawanakhilMM** [comment] 2023-03-27 12:38
Hey @bizob2828 @mrickard , currently facing the same issue SignatureDoesNotMatch
`The request signature we calculated does not match the signature you provided. Check your key and signing method.`

Currently using latest v3 aws-sdk  @ 3.299.0 and  newrelic @ 9.14.1 . And node version 18.12.1

As you can see in the screenshot it's happening because of this value.

![Screenshot 2023-03-27 at 5 58 48 PM](https://user-images.githubusercontent.com/96244231/227941558-27582ee8-777f-4918-b816-26a53643a4e6.png)

When we disable newrelic, preSignedURL is working perfectly fine.  with value of x-Amz-SignedHeaders as host

Is this related to this issue ?

**Comment by pawanakhilMM** [comment] 2023-03-27 12:38
Hey @bizob2828 @mrickard , currently facing the same issue SignatureDoesNotMatch
`The request signature we calculated does not match the signature you provided. Check your key and signing method.`

Currently using latest v3 aws-sdk  @ 3.299.0 and  newrelic @ 9.14.1 . And node version 18.12.1

As you can see in the screenshot it's happening because of this value.

![Screenshot 2023-03-27 at 5 58 48 PM](https://user-images.githubusercontent.com/96244231/227941558-27582ee8-777f-4918-b816-26a53643a4e6.png)

When we disable newrelic, preSignedURL is working perfectly fine.  with value of x-Amz-SignedHeaders as host

Is this related to this issue ?

**Comment by pawanakhilMM** [comment] 2023-03-27 17:05
@jmartin4563 
We are using `With Client and Command` approach as per the [documentation](https://aws.amazon.com/blogs/developer/generate-presigned-url-modular-aws-sdk-javascript/).

Here is the code snippet.
```
import { S3, GetObjectCommand, PutObjectCommand } from '@aws-sdk/client-s3';
import { getSignedUrl } from '@aws-sdk/s3-request-presigner';

async generateSignedUrl(
    operation: 'getObject' | 'putObject',
    params: {
      s3Key: string;
      bucketName: string;
      metadata?: { [key: string]: string };
    },
  ): Promise<string> {
       
      const s3Client= new S3({ region: 'us-east-1' });

      let command: GetObjectCommand | PutObjectCommand;

      switch (operation) {
        case 'getObject':
          command = new GetObjectCommand({
            Bucket: params.bucketName,
            Key: params.s3Key,
          });
          break;

        case 'putObject':
          command = new PutObjectCommand({
            Bucket: params.bucketName,
            Key: params.s3Key,
            Metadata: params.metadata,
          });
          break;
      }

      return getSignedUrl(s3Client, command, {
        expiresIn: 18000,
      });
  }
```

**Comment by jmartin4563** [comment] 2023-03-27 17:17
@pawanakhilMM thank you so much! i'll start digging into this

**Comment by jmartin4563** [comment] 2023-03-27 20:46
@pawanakhilMM I've confirmed the issue you and @marcoswca are seeing with Presigned URLs, since this is a separate issue from this current thread, I've opened up #1571 to keep things clean/separate, and will do my investigation/fixes off that issue. Thank you again for the report, closing this issue in lieu of #1571

**Closed by jmartin4563** 2023-03-27 20:46 UTC
Labels: bug
