### ISSUE TITLE
Logs are lost when streaming request is aborted

### ISSUE THREAD

**Issue by noseworthy** [newrelic/node-newrelic#1784] opened 2023-09-15 17:45 UTC
## Description

We're using the `node-newrelic` agent in our application and when the client disconnects from the server all logs for that request are lost.

We have an endpoint that streams responses to the client using [SSE](https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events/Using_server-sent_events). The client is using `axios` at v1.4.0 and can [abort the request to the server using an `AbortController`](https://axios-http.com/docs/cancellation). Our route roughly looks like this:

```typescript
import express from 'express';

import { logger } from './logger';
import { doStuff } from './generators/DoStuff';

const app = express();
const router = express.Router();

route.post('/doStuff', async (req, res, next) => {
  try {
    logger.info('starting to do stuff');
    res.set({
      'Content-Type': 'text/event-stream',
      'Cache-Control': 'no-cache',
      Connection: 'keep-alive',
    });
    res.flushHeaders();

    const abortController = new AbortController();
    req.socket.on('close', () => {
       if (!res.writableEnded) {
         logger.info('connection aborted');
         abortController.abort();
       }
    });

    // this block can take a minute or two
    for await (const chunk of doStuff()) {
      if (abortController.signal.aborted) {
        logger.info('aborting processing');
        break;
      }

      logger.info('writing chunk');
      res.write(chunk);
    }

    if (abortController.signal.aborted) {
      logger.info('request was interrupted!');
    } else {
      logger.info('done doing stuff!');
    }
    res.end();
  } catch (error) {
    logger.error('got an error doing stuff');
    next(error);
  }
});

app.use(router);

app.listen(PORT, () => {
  logger.info('server listening');
});
```

When a request completes normally, all the logs are written to newrelic, instrumented as expected with metadata. However, when a user aborts the request the only log that gets written is "connection aborted" and it's missing some instrumentation data like a trace id. We've set up a console log transport on winston as well. Since this is running in AWS ECS, we can see all of the console logs make their way into cloudwatch (missing the newrelic instrumentation of course)

## Expected Behavior

I'd expect all logs to get flushed to newrelic regardless if the request completed successfully or not.

## Steps to Reproduce

1. Start a request to server from javascript `fetch` api or `axios` to a streaming endpoint that takes a while to complete.
2. Cancel the request using `AbortController`
3. See that the client request cancels successfully
4. See that logs aren't flushed to newrelic

[NOTE]: # I'll try to build a sample application to reproduce this and I'll link it here if/when I get it set up.

## Your Environment

Node: v18.16.0
OS: Debian 12 bookworm
Express: 4.18.0
Winston: 3.8.1
Running on AWS ECS in a private subnet accessible via AWS ALB.

**Comment by bizob2828** [comment] 2023-09-15 18:34
@noseworthy I think this is because we don't have instrumentation around AbortController to propagate async context.  Once you have a repro app setup I'll be able to dig in more.  Have you tried to use v11 of the agent? The reason I say this is we updated our async context manager to default to one using AsyncLocalStorage and it might just work.

**Comment by noseworthy** [comment] 2023-09-15 20:45
Thanks for the input! We're on version 8.17.1 of the agent (should've included that in environment, sorry). Haven't tried v11. I'll have to give it a shot. Thanks!

My colleague is just putting in a change now that seems to get around this issue. If we call `newrelic.endTransaction()` manually in a `finally` block then it triggers the flush successfully. I am a little weary of calling that manually though.

Thanks again, I'll keep you updated!

**Comment by bizob2828** [comment] 2023-09-15 21:21
Ok, that's helpful and probably unrelated to async context propagation. We'll probably have to instrument the AbortController to do this. But I'll know for certain after you provide a repro app. This might turn into a feature request at that time.

**Comment by bizob2828** [comment] 2023-09-21 17:27
@noseworthy have you been able to create a reproduction case?

**Comment by noseworthy** [comment] 2023-09-21 17:34
Hey @bizob2828, thanks so much for following up. I tried a bunch over the weekend but wasn't able to replicate what's happening in our production system with a sample repo. Really not sure what's going on, but I haven't been able to hit on exactly what it is that produces this functionality.

We're real busy and have a workaround with the `newrelic.endTransaction()` call for now. So we haven't been able to try upgrading the agent yet.

I'll keep you posted when we get back to it. I'm not super familiar with how the agent works, so I'm very much talking from a place of ignorance here, but I'm not sure that instrumenting the `AbortController` is necessary? I'm able to get logs out of my sample application with no issue using the `AbortController`. The problem is that in production, if a request is interrupted for any reason (either the client closing the browser window, cancelling the request using an `AbortController`, or an exception is thrown) the logs never get flushed to newrelic.

Anyway, thanks again for following up, and sorry I don't have any more information. I will definitely update when I'm able to get back to it though!

**Comment by bizob2828** [comment] 2023-10-09 17:28
Ok. I'm going to close this issue, if you can provide a reproduction case, please reopen.

**Closed by bizob2828** 2023-10-09 17:28 UTC
Labels: bug, needs-triage
