### ISSUE TITLE
The pg instrumentation includes the waiting time in the client's internal queue when recording query runtime

### ISSUE THREAD

**Issue by papandreou** [newrelic/node-newrelic#345] opened 2020-05-15 10:35 UTC
Got a bit of a jumpscare the other day when we refactored one of our apps in a way that caused us to issue more `pg` client calls in parallel. The change didn't affect the number of queries being run or their actual execution times in the database, but newrelic's graphs reported a severe performance regression:

![Screen Shot 2020-05-15 at 12 23 48](https://user-images.githubusercontent.com/373545/82040491-f3f6d980-96a6-11ea-8da9-f1b14803d3be.png)

Since you cannot multiplex parallel queries into a single postgres connection, the `pg` client has an internal waiting queue so that each query ends up getting exclusive access: https://github.com/brianc/node-postgres/blob/bf469399b88bcdf86eff096fd0dd05684adc1117/packages/pg/lib/client.js#L557

However, `node-newrelic`'s instrumentation of the `pg` module only shims the `query` method: https://github.com/newrelic/node-newrelic/blob/18de96b2bb37691d6820ad806644753f7cc237fe/lib/instrumentation/pg.js#L54-L60

As far as I can tell, the consequence is that the time the query spends waiting in `queryQueue` will be counted as part of its runtime. That also explains why the actual request response time reported in the chart above is way lower than the height of the solid colors.

It looks like the instrumentation has to dive one step deeper to account for this.

**Comment by carlonewrelic** [comment] 2020-05-18 17:08
Hi @papandreou 
Thank you for surfacing this issue.  We will enter a bug to research and fix the `pg` instrumentation.  In the meantime, if you feel like you understand the issue well and want to attempt to fix the instrumentation, we welcome contributions to the code.

**Comment by carlo-808** [comment] 2021-02-08 23:12
We were able to reproduce the behavior and a reproduction is here: https://github.com/carlo-808/pg-query-timing-repro

I suspect that we will need to instrument the `Query` object itself possibly around the `submit` [function](https://github.com/brianc/node-postgres/blob/bf469399b88bcdf86eff096fd0dd05684adc1117/packages/pg/lib/query.js#L151). We will get this issue further prioritized.

**Comment by andreas** [comment] 2021-04-22 19:02
Hey @carlo-808 - any update on this issue? TIA 🙏🏻

**Comment by carlo-808** [comment] 2021-04-22 20:20
Hi @andreas, unfortunately this work was put on the side due to other pressing issues. But, I hope to be circling back to it soon. I found a better location to instrument but we don't have all the information needed at that point. I'll be looking into ways to pipe that data to a segment created at the new query instrumentation location.

**Comment by andreas** [comment] 2021-04-23 11:40
@carlo-808, thanks for the prompt reply!

**Comment by carlo-808** [comment] 2021-05-14 22:20
@andreas and @papandreou I'm slowly making progress on this. I just have a question, are you using the `pg` module with the `pg-native` module using the `NODE_PG_FORCE_NATIVE` env var? We currently have special instrumentation for that case. I'm focused on the non `pg-native` instrumentation.

**Comment by papandreou** [comment] 2021-05-14 22:50
Sounds good! We currently aren't using the `pg-native` module, so that's perfect.

**Comment by carlo-808** [comment] 2021-05-14 22:52
Excellent! Thanks for the quick response!

**Comment by carlo-808** [comment] 2021-06-11 21:54
@andreas and @papandreou sorry it took so long for an update. I tried adding instrumentation at the `Connection.query` level and under heavy request/query load some queries get nested under a different transaction. This indicates to me that the  level the Connection object is shared across client calls. This might be why Open Telemetry instruments at the same level the Node Agent is originally doing. If you're curious, here's the branch I'm working on and the experimental instrumentation:
https://github.com/carlo-808/node-newrelic/blob/pg-query/lib/instrumentation/pg.js#L112
We may need to roll this into a bigger effort but right now I'm concerned about this segment bleed over.

**Comment by papandreou** [comment] 2021-06-13 08:19
Maybe something crazy like temporarily shimming `Connection#queryQueue.push` while `originalQueryMethod` is running so you can grab hold of the `Query` instance that gets added to the client's query queue? That should allow you to attach a symbol property referencing the transaction segment of the original `Connection#query` call context, which you can then get your hands on in the shimmed `Connection#query`?

**Comment by carlo-808** [comment] 2021-06-15 23:25
Unfortunately we need to shim when the node-postgres module loads. I'm doing a little bit more experimenting to see if I can suss things out a bit. Will keep you posted.

**Comment by carlo-808** [comment] 2021-07-14 20:17
Moving this issue back to backlog. Need to work on #786 before continuing this work.

**Comment by papandreou** [comment] 2021-09-30 07:29
@carlo-808, still eagerly awaiting a solution 🤗 🍿

**Comment by bizob2828** [comment] 2021-09-30 14:05
Thanks for reaching out @papandreou. I moved this close to the top of our backlog.  We had other priorities come in and this may have got bumped further down the stack than expected.

**Closed** 2021-10-07 15:06 UTC
Labels: bug
