### ISSUE TITLE
TransactionHandleStub

### ISSUE THREAD

**Issue by frodrigueza** [newrelic/node-newrelic#290] opened 2019-07-26 16:04 UTC
Im performing a load test to my newRelic monitored app. When the requests are performed sequentially, an instance of `TransactionHandle` is retrieved by the `newrelic.getTransaction()` function.

The problem arises when I perform some concurrent requests to my server, the method `newrelic.getTransaction()` returns an instance of `TransactionHandleStub`. Half of them to be precise.

Here it says that it could be because no transaction is being tracked at the time I am calling the function: https://newrelic.github.io/node-newrelic/docs/lib_transaction_handle.js.html (line 58)

I think this is why in my dashboard I see unrecognized transactions:
![image](https://user-images.githubusercontent.com/5264663/61964973-1fd09380-af9d-11e9-911b-2e866418c5e1.png)

Any idea? Thanks!

**Comment by astormnewrelic** [comment] 2019-08-05 18:36
@frodrigueza -- nice to meet you, and thanks for reaching out!

For starters, `<official-voice>` if you need Official Support for the agent the quickest way to resolve a problem is to contact support at [https://support.newrelic.com/](https://support.newrelic.com/).  `</official-voice>`

Regarding the behavior you described, there are circumstance where, depending on how you're achieving your concurrency, that NodeJS can lose track of the transaction.  We call this transaction state loss and your description sounds like a classic case. 

This mainly happens when code "Crosses asynchronous boundaries" (i.e. when work gets shuttled off to the event loop via setTimeout, setImmediate, or one of its ilk).  We take extra effort to prevent this in the Agent, but since every framework handles this sort of work differently, it's a sort of a whack-a-mole situation.  

Is it possible to boil your problem down to a simple reproducible code sample you can share here?  We might be able to spot an obvious problem and/or help you with an unofficial work around.

**Comment by astormnewrelic** [comment] 2019-08-21 22:35
We're going to close this out for now, but please free to restart the conversation when/if you have the time or interest.

**Closed by astormnewrelic** 2019-08-21 22:35 UTC
