### ISSUE TITLE
gRPC record_errors setting is not documented

### ISSUE THREAD

**Issue by stellar-scottreed** [newrelic/node-newrelic#1400] opened 2022-11-04 17:00 UTC
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

[NOTE]: Our newrelic client was updated on a deployment and we suddenly were receiving lots of gRPC errors. Our servers handle errors by passing a gRPC status code to the client. We were not expecting sending a non-zero status code would send an error to newrelic. I saw the grpc.record_errors flag in recent release notes and suspect this is the reason why. This flag is not documented anywhere on the newrelic website or in this repos documentation. This bug report is to request that this functionality be documented.

Alternatively, perhaps record_errors should default to false, given that for a long time we did not have to set this setting explicitly to false in order to not receive gRPC errors, which has caused a lot of spam on our newrelic slack channel.

[TIP]:  # ( Do NOT share sensitive information, whether personal, proprietary, or otherwise! )

## Expected Behavior

[NOTE]: The grpc.record_errors flag to be documented.

## [Troubleshooting](https://discuss.newrelic.com/t/troubleshooting-frameworks/108787) or [NR Diag](https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/troubleshooting/new-relic-diagnostics) results

[NOTE]: # ( Provide any other relevant log data. )
[TIP]:  # ( Scrub logs and diagnostic information for sensitive information )

## Steps to Reproduce

[NOTE]: # ( Please be as specific as possible. )
[TIP]:  # ( Link a sample application that demonstrates the issue. )

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )

* ex: Browser name and version:
* ex: Node version:
* ex: Operating System and version:

## Additional context

[TIP]:  # ( Add any other context about the problem here. For example, relevant community posts or support tickets. )

**Comment by jordigh** [comment] 2022-11-04 17:07
It is documented:

https://docs.newrelic.com/docs/apm/agents/nodejs-agent/installation-configuration/nodejs-agent-configuration/#grpc_server

Is our docs website difficult to find? Should we fix that?

**Comment by stellar-scottreed** [comment] 2022-11-04 17:11
> It is documented:
> 
> https://docs.newrelic.com/docs/apm/agents/nodejs-agent/installation-configuration/nodejs-agent-configuration/#grpc_server
> 
> Is our docs website difficult to find? Should we fix that?

Thanks for pointing that out! I searched on Google and did not find it. Most of the results were the release blog, I see the documentation link you linked to now. I suppose I missed it because it's not in the search description.

Is it a regression that we are suddenly getting so many errors reported after an update when previously we did not?

**Comment by jordigh** [comment] 2022-11-04 17:17
I don't know if I would call that a regression. gRPC just wasn't instrumented before, so suddenly instrumenting it shouldn't be a regression. New Relic defaults to reporting errors elsewhere. The gRPC standard defines anything nonzero as an error, just like Unix `grep` uses nonzero exit status to indicate that nothing was found.

Is it common to use nonzero exit codes in a non-error way? I would like to hear from more customers if this is the usual way to use gRPC, despite what the standard says.

**Comment by stellar-scottreed** [comment] 2022-11-04 17:27
I suppose it's one of those cases where it did not function as documented for so long, that it was assumed that the non-documented functionality was the proper functionality :).

We have an API that communicates with separate microservices, these microservices catch different error classes and use nonzero exit codes to communicate that an error occurred to the API, with metadata attached for more detailed information, so that this error could be communicated to the user. I don't have an answer for how common this is for other organizations.

**Comment by jordigh** [comment] 2022-11-04 17:29
It might make sense to handle this elsehow. Maybe a list of error codes to ignore or maybe work harder to determine if the error has already been handled in some other way.

Either way, that seems like a separate issue altogether. Might I trouble you with opening a new case about that, if you think that is something that we should do? I'll close this issue, since the problem reported of lacking documentation does not seem to be the actual issue.

**Closed by jordigh** 2022-11-04 17:29 UTC
Labels: bug, needs-triage

**Comment by stellar-scottreed** [comment] 2022-11-04 17:36
@jordigh https://github.com/newrelic/node-newrelic/issues/1401
