### ISSUE TITLE
Prisma instrumentation no longer works on >5.9.0

### ISSUE THREAD

**Issue by bizob2828** [newrelic/node-newrelic#1984] opened 2024-01-30 16:50 UTC
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description
Prisma just released [5.9.0](https://github.com/prisma/prisma/releases/tag/5.9.0).  It looks like they restructured exports to where instrumenting `@prisma/client` is not sufficient.  

## Expected Behavior

Instrumentation of prisma 5.9.0+ will still function

## Steps to Reproduce

```sh
cd test/versioned/prisma
npm i prisma@latest @prisma/client@5.9.0 --no-save --no-package-lock
node prisma.tap.js
```

## Additional context
This will be an exercise in figuring out the appropriate paths to give to `shimmer.registerInstrumentations`. I've tried the following so far and it's very hard to determine the _right_ paths.  [WIP branch](https://github.com/bizob2828/node-newrelic/commit/b37e4a75416db9038d341654eb4b4e017acacbf1)

You can see the export changed

5.8.1 with debug on in require-in-the-middle

```sh
2024-01-30T16:54:52.135Z require-in-the-middle resolved filename to module: @prisma/client (id: @prisma/client, resolved: @prisma/client, basedir: /Users/revans/code/release/node-newrelic/test/versioned/prisma/node_modules/@prisma/client)
2024-01-30T16:54:52.136Z require-in-the-middle calling require hook: @prisma/client
```

5.9.0

```sh
2024-01-30T16:39:22.506Z require-in-the-middle resolved filename to module: @prisma/client (id: @prisma/client, resolved: @prisma/client/default, basedir: /Users/revans/code/pull-requests/node-newrelic/test/versioned/prisma/node_modules/@prisma/client)
2024-01-30T16:39:22.506Z require-in-the-middle ignoring require of non-main module file: /Users/revans/code/pull-requests/node-newrelic/test/versioned/prisma/node_modules/@prisma/client/index.js
```

**Comment by jsumners-nr** [comment] 2024-01-30 17:18
The issue stems from https://github.com/prisma/prisma/commit/9c14954337375caaa880c92003a0c8fca35afde5#diff-26d3d28d31824ef26252df77cca08d24faea8451cb8fd3ffee2000f9e496daa0 introduced by PR https://github.com/prisma/prisma/pull/22630.

**Comment by millsp** [comment] 2024-01-30 23:40
In order to find out what went wrong, I created a minimal reproduction to try and understand how your tests were failing. Thanks to  the context you left in this issue and elsewhere, I took a look at how you were resolving and injecting the Prisma Client. Then I came up with this reproduction:

```ts
// index.ts

import { Hook } from 'require-in-the-middle' 

new Hook(['@prisma/client'], {
}, function (exports, name) {
  console.log('loading %s', name) 

  return exports
})

require('@prisma/client')
```

With `prisma@5.8.0` it produced the following output:

```sh
$ node -r esbuild-register index.ts

loading @prisma/client
```

With `prisma@5.9.0` it produced no output at all:
```sh
$ node -r esbuild-register index.ts
```

Somehow according to `Hook`, nothing was loaded, and that's obviously not true. To investigate, I then passed `internals: true` as a `Hook` option, that surprisingly made it display something, so it seemed like I hit a bug or an edge case?

```ts
new Hook(['@prisma/client'], {
  internals: true
}, function (exports, name) {
  console.log('loading %s', name) 

  return exports
})
```

```sh
$ node -r esbuild-register index.ts

loading @prisma/client/runtime/library.js
loading @prisma/client/default.js
```

Further down, I tried to understand why this would be an edge case if other libraries like `xstate` or `preact` seemed to work just fine with `Hook`. After proceeding by elimination, I found one key difference between `@prisma/client`'s exports map and other libs. In short:

The `main` field in `@prisma/client` was pointing to `index.js` while the `exports` was pointing the default to `default.js`. To my surprise this was the reason. I pointed `main` to `default.js` as well and `Hook` started working again. I am not entirely sure why that is the case, as `index` and `default` are equivalent files too, and that `require` would go through the exports map too.

That explained, I mostly came here to share and ask you if you could please try the integration version I have been working on. The reproduction I had at hand may not reflect your full setup, so if you can install both `prisma` and `@prisma/client` with `5.10.0-integration-fix-client-exports-map.4` to give it a shot and let me know, that would be amazing. Thanks!

**Comment by millsp** [comment] 2024-01-31 00:18
After taking a look at the source code of `require-in-the-middle`, it does expect the resolved `exports` and `main` to be the [same](https://github.com/elastic/require-in-the-middle/blob/main/index.js#L250), so that confirms what I wrote above. Given this encoded behavior, this is how I would do it:

```ts
import { Hook } from 'require-in-the-middle' 

async function main() {
  new Hook(['@prisma/client/default'], {
    internals: true
  }, function (exports, name, basedir) {
    console.log('loading %s', name) 

    return exports
  })

  require('@prisma/client')
}

void main()
```

Let me know if that works for you.

**Comment by bizob2828** [comment] 2024-01-31 01:53
@millsp thanks for taking time to triage and fix.  We do not pass `internals: true` to require-in-the-middle for "reasons". However I was able to determine `5.10.0-integration-fix-client-exports-map.4` fixes our issues with no changes. do you plan on releasing this in 5.10.0? or a 5.9.1? How I tested was

```sh
cd test/versioned/prisma
npm i prisma@latest @prisma/client@5.10.0-integration-fix-client-exports-map.4 --no-save --no-package-lock
node prisma.tap.js
```

**Comment by millsp** [comment] 2024-01-31 02:16
Happy that we found a solution, and thanks for confirming the fix.
We are planning to release this via `5.9.1` once the PR is ready.

**Comment by bizob2828** [comment] 2024-01-31 02:29
This issue will serve to update the version ranges for our prisma versioned tests and just skip 5.9.0

**Closed** 2024-02-01 17:32 UTC
Labels: bug, needs-triage
