### ISSUE TITLE
Memory Leak with KafkaJS Causing Application Crash

### ISSUE THREAD

**Issue by ffc-gwakefield** [newrelic/node-newrelic#2332] opened 2024-07-08 15:02 UTC
## Description

NewrelicJS fills up the heap and crashes applications when paired with KafkaJS in an Express service. This is due to faulty code in KafkaJS's  `checkPendingRequests` loop that causes Newrelic to shim setTimeout in a transaction and create a `SegmentTrace` object. Because of the flaw in KafkaJS with a runaway loop, thousands of these being created and quickly run out of memory in your Node heap on the server. The transaction doesn't start recording segments until the express http endpoint is hit.

## Expected Behavior

Newrelic can manage runaway loops like from Kafka without maxing the heap, or have a feature/config to limit this behavior.

## [Troubleshooting](https://discuss.newrelic.com/t/troubleshooting-frameworks/108787) or [NR Diag](https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/troubleshooting/new-relic-diagnostics) results

Running a Node heapprofile or cpuprofile for a couple seconds shows that Newrelic is using all of the CPU and memory for the trace segment calls. I captured a few and got the same results. Interestingly with the latest package, there was a large increase in CPU time garbage collecting but it did not help. Heap still filled up and eventually crashed the app.

![image](https://github.com/newrelic/node-newrelic/assets/175027615/4ec82a5b-6766-4d29-a0d4-4d5e216b3010)
![image](https://github.com/newrelic/node-newrelic/assets/175027615/9b5219af-9662-4bf1-b82a-92eb2cb97c6c)

Usually trying to capture an entire heapsnapshot results in the app crashing as it's already using most of the machine's memory. But I managed to get one before it completely bloated the memory and with enough swap space:

![image](https://github.com/newrelic/node-newrelic/assets/175027615/92c3e8b4-5a85-4670-9027-9fc08167ebc1)

## Steps to Reproduce

1. Requires an express service with KafkaJS (from tulios).
2. Hit the express endpoint, and send a kafka message to a downstream service that never responds.
3. Observe memory leak

## Your Environment

RHEL 9 Linux L2
Node v18.20.2
@nestjs/axios ^3.0.0
@nestjs/core ^10.3.7
kafkajs ^2.2.0

## Additional context

I realize the main problem is kafkajs which seems to be an unmaintained library now, but this is causing newrelic to spin out of control. Is there any way to mitigate this for bad acting software like kafkajs?

**Comment by bizob2828** [comment] 2024-07-08 15:49
@ffc-gwakefield Can you please provide a reproduction application exhibiting this behavior?  We _might_ be able to fix but based on what you're saying it sounds like it's a kafkajs issue which we may be compounding.

**Comment by ffc-gwakefield** [comment] 2024-07-08 16:04
Here is the link to the kafkajs issue: https://github.com/tulios/kafkajs/issues/1704

I'll get back with the team and see if we can create a reproduction application for you to use. 

In the meantime, the issue on kafkajs has a fork and failing test, along with the fix for kafkajs if that's useful.

**Comment by bizob2828** [comment] 2024-07-08 16:08
Thanks @ffc-gwakefield. In the meantime I recommend you just disable the kafkajs feature flag within the agent:  `feature_flag.kafka_instrumentation = false`

**Comment by bizob2828** [comment] 2024-07-08 21:00
@ffc-gwakefield a reproduction application would really help here. I can't seem to reproduce

**Comment by ffc-gwakefield** [comment] 2024-07-09 13:33
Thank you, @bizob2828 for your prompt replies and looking into this. It's unfortunate that you couldn't replicate it because our teams our quite busy since our projects are behind due to this issue. But hopefully we can build something when things settle down here.

**Comment by bizob2828** [comment] 2024-07-09 13:49
I'm sorry you're all busy but I can't do much without a repro case. Seems like the better angle may be to get Kafka to fix the issue. We're just compounding the problem as we instrument setTimeout.

**Comment by bizob2828** [comment] 2024-08-01 17:39
Closing due to lack of repro case. If you can provide repro, please feel free to reopen

**Closed by bizob2828** 2024-08-01 17:39 UTC
Labels: bug, cannot reproduce
