### ISSUE TITLE
runInContextCb error using composable-middleware in node app running on newrellic V12

### ISSUE THREAD

**Issue by karankapur999** [newrelic/node-newrelic#2806] opened 2024-11-29 09:29 UTC
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )
After upgrading **newrelic** from V10.0 ^---> V12.0^ in node js app, app started getting errors
## Description

[NOTE]: # ( Describe the problem you're encountering. )
I am using composable-middleware and the app crashes with attached errors on new version 

## Expected Behavior

[NOTE]: # ( Tell us what you expected to happen. )

## [Troubleshooting](https://discuss.newrelic.com/t/troubleshooting-frameworks/108787) or [NR Diag](https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/troubleshooting/new-relic-diagnostics) results

[NOTE]: # ( Provide any other relevant log data. )
[TIP]:  # ( Scrub logs and diagnostic information for sensitive information )

## Steps to Reproduce

[NOTE]: # ( Please be as specific as possible. )
<img width="1233" alt="Screenshot 2024-11-29 at 2 55 54 PM" src="https://github.com/user-attachments/assets/d474110b-672d-42e4-983d-ac1b021df605">

[TIP]:  # ( Link a sample application that demonstrates the issue. )

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )

* ex: Browser name and version:
* ex: Node version:
* ex: Operating System and version:

## Additional context

[TIP]:  # ( Add any other context about the problem here. For example, relevant community posts or support tickets. )
<img width="1233" alt="Screenshot 2024-11-29 at 2 55 54 PM" src="https://github.com/user-attachments/assets/1639cf61-f93c-4979-8b60-53301cb40cbf">

**Comment by bizob2828** [comment] 2024-12-02 13:34
@karankapur999 can you provide a reproduction case. I'm not sure what composable-middleware means in this context.

**Comment by jsumners-nr** [comment] 2024-12-02 13:54
👋 thank you for the report. Please provide a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example). Doing so will help us diagnose the issue. It should be the bare minimum code needed to trigger the issue, and easily runnable without any changes or extra code.

You may use a GitHub repository to host the code if it is too much to fit into a [code block](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks) (or two).

**Comment by bizob2828** [comment] 2024-12-03 15:23
@karankapur999 as @jsumners-nr we need a reproduction case. I cannot reproduce by doing:

```js
const express = require('express')
const composableMw = require('composable-middleware')
const app = express()
const { PORT = 3000 } = process.env

const mw = composableMw().use(function(req, res, next) {
  console.log('in first')
  next()
}).use(function second(req, res, next) {
  console.log('in second')
  next()
})

app.use(mw)

app.get('/named-route', (req, res) => {
  res.send('hi')
})


app.listen(PORT, () => console.log(`Example app listening on port ${PORT}!`))
```

**Comment by bizob2828** [comment] 2024-12-16 22:25
Closing because we cannot reproduce. If you can provide a reproducation case @karankapur999, please link it and re-open issue

**Closed by bizob2828** 2024-12-16 22:25 UTC
Labels: bug, cannot reproduce
