### ISSUE TITLE
Issue with post request to collector-010.newrelic.com throwing timeout after ~23min

### ISSUE THREAD

**Issue by mauricionr** [newrelic/node-newrelic#449] opened 2020-07-30 20:57 UTC
i found on datadog some traces from newrelic calling collector-010.newrelic.com with `http` using the port `443`

https://github.com/newrelic/node-newrelic/blob/b66180a2a315aafbcf47ff8245ecd8c5476aa06b/lib/collector/api.js#L192

<img width="473" alt="Screen Shot 2020-07-30 at 17 54 04" src="https://user-images.githubusercontent.com/2263551/88973706-e99fb100-d28d-11ea-82f4-35e8d811e9b7.png">

**Comment by astormnewrelic** [comment] 2020-07-31 14:44
Thanks @mauricionr for reporting -- that's definitely not how things should be working.  That collector URL is where New Relic reports its data, and all those connections were make https only a number of years ago.  That your application or the agent is trying to connect via HTTP definitely points to a bug somewhere 

Unfortunately there's not lot to go on here -- if you could answer a few questions we might be able to zero in on a reproduction. Once we have a reproduction we'll be able to move on with a fix. 

1. Ideally -- can you share a reproduction of this behavior with us?

2. If not -- what version of the agent are you running?

3. You've blocked out the the `service` parameter in your screen shot.  Can you share what this is, or does it contain information that's sensitive to your application?

4. Is this the only example of this behavior, or do you see this with other values in the `service` parameter?

**Comment by mauricionr** [comment] 2020-07-31 15:12
> Thanks @mauricionr for reporting -- that's definitely not how things should be working. That collector URL is where New Relic reports its data, and all those connections were make https only a number of years ago. That your application or the agent is trying to connect via HTTP definitely points to a bug somewhere
> 
> Unfortunately there's not lot to go on here -- if you could answer a few questions we might be able to zero in on a reproduction. Once we have a reproduction we'll be able to move on with a fix.
> 
> 1. Ideally -- can you share a reproduction of this behavior with us?
> 2. If not -- what version of the agent are you running?
> 3. You've blocked out the the `service` parameter in your screen shot.  Can you share what this is, or does it contain information that's sensitive to your application?
> 4. Is this the only example of this behavior, or do you see this with other values in the `service` parameter?

Thanks for you quick response @astormnewrelic 

1. the behaviour occurs in production when new_relic try to send data to the collector api
2. i've notice using the latest version 6.11.0
3. the service params it's just a name of our service running on k8s(service: greyhound)
4. there's a lot of call from new_relic in this situation hanging the request about ~15min ~25min

<img width="549" alt="Screen Shot 2020-07-31 at 12 10 13" src="https://user-images.githubusercontent.com/2263551/89048988-eb698300-d326-11ea-9a4f-900633b7a4c6.png">


<img width="550" alt="Screen Shot 2020-07-30 at 17 53 33" src="https://user-images.githubusercontent.com/2263551/89049048-06d48e00-d327-11ea-80cb-b646240eedcf.png">

**Comment by astormnewrelic** [comment] 2020-07-31 17:04
Thanks @mauricionr -- that's useful information.

So -- TL;DR; -- something doesn't add up here.  I'm going to describe what I see in the hopes it might trigger some additional information you could share.  If not, we may be at the point where our formal support channels are a better place to bring this (unless you've already posted to [our forum](https://discuss.newrelic.com/) or [support portal](support.newrelic.com/)?)

Here's what we have -- 

1. Modern Agents (6.11 is modern) only talk to the collector via `https`, not `http`
2. You can see this in the `lib/collector/remote-method` module. The agent [makes  collector requests](https://github.com/newrelic/node-newrelic/blob/b66180a2a315aafbcf47ff8245ecd8c5476aa06b/lib/collector/remote-method.js#L256) using [the https](https://github.com/newrelic/node-newrelic/blob/b66180a2a315aafbcf47ff8245ecd8c5476aa06b/lib/collector/remote-method.js#L10) module. This built-in node modules is responsible for adding the `https` to the hostname
3. Your app/agent appears to be making requests to this collector host via `http`, not `https`

It doesn't seem like it's possible for the agent alone to being doing this.  The only two things I can think that might be the root cause are

1. Someone added code to your application/service that's directly calling the collector URL outside of the agent 

2. Some other agent (maybe Datadog's?) is interfering with the https module in a way that conflicts with this code

Neither are these are things that are easily addressable via the agent. 

Does any of that shake anything loose in your head @mauricionr?

**Comment by mauricionr** [comment] 2020-07-31 17:28
@astormnewrelic Thanks!

>1. Someone added code to your application/service that's directly calling the collector URL outside of the agent
no code from our side calling newrelic api directly.

>2. Some other agent (maybe Datadog's?) is interfering with the https module in a way that conflicts with this code
we will investigate, but it seems to be a conflict

Thanks again 🍻 !

**Comment by astormnewrelic** [comment] 2020-07-31 18:39
🍻 to you too :). We're going to close this out for now, but if you need more help don't hesitate to open a new issue or response here.

**Closed by astormnewrelic** 2020-07-31 18:39 UTC
Labels: bug
