### ISSUE TITLE
Crash in elasticsearch instrumentation with null body.

### ISSUE THREAD

**Issue by villelahdenvuo** [newrelic/node-newrelic#1809] opened 2023-10-13 13:47 UTC
## Description

https://github.com/newrelic/node-newrelic/blob/main/lib/instrumentation/%40elastic/elasticsearch.js#L58

```
error.stack: "TypeError: Cannot convert undefined or null to object
	at Function.keys (<anonymous>)
	at Transport.queryParser (/mnt/ramdisk/ecom-api/node_modules/newrelic/lib/instrumentation/@elastic/elasticsearch.js:58:49)
	at DatastoreShim.parseQuery (/mnt/ramdisk/ecom-api/node_modules/newrelic/lib/shim/datastore-shim.js:456:35)
	at Transport.queryRecord (/mnt/ramdisk/ecom-api/node_modules/newrelic/lib/shim/datastore-shim.js:670:25)
	at Transport.wrapper (/mnt/ramdisk/ecom-api/node_modules/newrelic/lib/shim/shim.js:850:33)
	at IndicesApi.indicesExistsApi [as exists] (/mnt/ramdisk/ecom-api/node_modules/@elastic/elasticsearch/api/api/indices.js:361:25)
```

## Expected Behavior

No error.

## Steps to Reproduce

Calling `indicesExistsApi` in `@elastic/elasticsearch`

**Comment by mrickard** [comment] 2023-10-13 13:58
Thank you for the report, @villelahdenvuo , and sorry for the trouble. We'll prioritize a fix for this.

**Comment by villelahdenvuo** [comment] 2023-10-13 14:07
@mrickard Luckily it got caught in our E2E tests. 😄

**Comment by bizob2828** [comment] 2023-10-13 16:49
@villelahdenvuo which version of `@elastic/elasticsearch` are you using?

**Comment by villelahdenvuo** [comment] 2023-10-13 16:54
@bizob2828 @elastic/elasticsearch@7.10.0 as we're stuck on ES7 and would need to migrate to AWS OpenSearch.

**Comment by bizob2828** [comment] 2023-10-13 16:56
@villelahdenvuo ok, I think that might be the issue. We only support 8.0.0+, but unfortunately we didn't lock down the instrumentation but we built it with v8.0.0+. We will talk with our product manager about if we will support pre 8.0.0

**Comment by villelahdenvuo** [comment] 2023-10-13 17:02
@bizob2828 Regardless I think it's a good practice to check for null when doing `typeof x === 'object'`. Don't you think?

**Comment by bizob2828** [comment] 2023-10-13 17:03
@villelahdenvuo for sure. we were just trying to reproduce with an integration test and could not based on your stack

**Comment by villelahdenvuo** [comment] 2023-10-13 17:50
Btw I can upgrade to 7.17.13, I had misconfigured Dependabot to ignore minor updates.

**Comment by mrickard** [comment] 2023-10-23 17:43
@villelahdenvuo This has been released with agent version 11.3.0. Thank you for the report!

**Comment by bartosz347** [comment] 2023-12-07 10:27
Hi @mrickard 

I've tried to upgrade NewRelic from v11.1.0 to v11.5.0, but I'm still getting errors related to ElasticSearch.

We're using `elasticsearch` v7.13.0, here is the stack trace:
```
TypeError: Cannot read properties of null (reading 'then')
at Object.then (/app/node_modules/@elastic/elasticsearch/lib/Transport.js:156:18)
at DatastoreShim.interceptPromise (/app/node_modules/newrelic/lib/shim/shim.js:1713:8)
at DatastoreShim.bindPromise (/app/node_modules/newrelic/lib/shim/shim.js:1729:15)
at Transport._doRecord (/app/node_modules/newrelic/lib/shim/shim.js:937:22)
at Transport.wrapper (/app/node_modules/newrelic/lib/shim/shim.js:887:24)
at Client.bulkApi [as bulk] (/app/node_modules/@elastic/elasticsearch/api/api/bulk.js:67:25)
at tryBulk (/app/node_modules/@elastic/elasticsearch/lib/Helpers.js:691:16)
at bulkOperation (/app/node_modules/@elastic/elasticsearch/lib/Helpers.js:658:7)
at send (/app/node_modules/@elastic/elasticsearch/lib/Helpers.js:629:9)
at iterate (/app/node_modules/@elastic/elasticsearch/lib/Helpers.js:543:9)
at async XXX.YYY (/app/dist/XXX)
at async XXX.ZZZ (/app/dist/XXX)
```

Would you be able to help with this? I'm happy to create a new issues if you prefer.

**Comment by bartosz347** [comment] 2023-12-07 16:32
@mrickard Here is a sample code that is failing when NewRelic (`v11.6.0`) is enabled:

```js
await elasticClient.helpers.bulk({
  datasource: [
    {
      amount: 123,
    },
  ],
  onDocument() {
    return [
      {
        update: { _index: 'xxx', _id: 'yyyyyy' },
      },
      { doc_as_upsert: true },
    ];
  },
});
```
[Client docs](https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/client-helpers.html#_update_2)

I'm running Elasticsearch locally with Docker `image: elasticsearch:7.13.0` and and have `@elastic/elasticsearch@7.13.0` package installed.

**Comment by mrickard** [comment] 2023-12-07 18:18
@bartosz347 Thank you for the repro!

Were you successfully using our instrumentation prior to v11.6.0 of the agent?

**Comment by bartosz347** [comment] 2023-12-08 08:08
> Were you successfully using our instrumentation prior to v11.6.0 of the agent?

@mrickard No, we first tried to upgrade to v11.2.1, but due to ElasticSearch errors we've reverted to v11.1.0. This week I tried to upgrade to v11.6.0. Some ES queries started to work but not all of them.

**Comment by mrickard** [comment] 2023-12-12 18:32
@bartosz347 Would you be able to open this as a new issue?

**Closed** 2023-12-12 18:41 UTC
Labels: bug

**Comment by bartosz347** [comment] 2023-12-12 18:55
> @bartosz347 Would you be able to open this as a new issue?

Done – https://github.com/newrelic/node-newrelic/issues/1908
