### ISSUE TITLE
Obfluscation causes RangeError: Maximum call stack size exceeded error on big queries

### ISSUE THREAD

**Issue by tomashanacek** [newrelic/node-newrelic#446] opened 2020-07-28 16:23 UTC
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

Obfluscation RegExp causes `RangeError: Maximum call stack size exceeded` error on big queries

[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT share sensitive information, whether personal, proprietary, or otherwise! )

## Expected Behavior

[NOTE]: # ( Tell us what you expected to happen. )

## [Troubleshooting](https://discuss.newrelic.com/t/troubleshooting-frameworks/108787) or [NR Diag](https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/troubleshooting/new-relic-diagnostics) results

[NOTE]: # ( Provide any other relevant log data. )
[TIP]:  # ( Scrub logs and diagnostic information for sensitive information )

## Steps to Reproduce

I'm able to replicate the issue by running

```javascript
("'"+(new Array(8400000).fill('a')).join('')+"'").replace(/'(?:[^']|'')*?(?:\\'.*|'(?!'))/gi, '?')
```

I think that`|''` part of single quote regexp is causing the issue

https://github.com/newrelic/node-newrelic/blob/main/lib/util/sql/obfuscate.js#L10

[NOTE]: # ( Please be as specific as possible. )
[TIP]:  # ( Link a sample application that demonstrates the issue. )

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )

* ex: Browser name and version:
* ex: Node version:
* ex: Operating System and version:

## Additional context

[TIP]:  # ( Add any other context about the problem here. For example, relevant community posts or support tickets. )

**Comment by astormnewrelic** [comment] 2020-07-29 15:55
Nice to meet you @tomashanacek and thanks for the bug report -- we can confirm the regular expression

    ("'"+(new Array(8400000).fill('a')).join('')+"'").replace(/'(?:[^']|'')*?(?:\\'.*|'(?!'))/gi, '?')

does seem to destroy the call stack using stock settings. 

    $ node
    > ("'"+(new Array(8400000).fill('a')).join('')+"'").replace(/'(?:[^']|'')*?(?:\\'.*|'(?!'))/gi, '?')
    Thrown:
    RangeError: Maximum call stack size exceeded
        at String.replace (<anonymous>)

I also tried bumping the `node --stack-size=...` limit up, but the code still seemed to reach its maximum stack size.  This probably means we're dealing with one of those infinite/near-infinite [NFA](https://en.wikipedia.org/wiki/Nondeterministic_finite_automaton) recursion states.

We have a few questions that can help us zero in on the right solution -- if you can answer as many of these as you have time for it would be a big help to us. 

- A string 8,400,000 characters long is around 8.4MB -- what framework are you using that generates a SQL query this large -- or is this a query that's manually built?

- Is this something you can isolate into to a small full reproduction case and share with us?

- Does this crash the agent? Or does node spew an error and the agent keeps chugging along?

**Comment by tomashanacek** [comment] 2020-07-30 09:19
> A string 8,400,000 characters long is around 8.4MB -- what framework are you using that generates a SQL query this large -- or is this a query that's manually built?

I don't think we are actually having this big queries, it was just example I created to demonstrate the issue, anyway we are running some bigger sql queries with a lot of uuids

> Is this something you can isolate into to a small full reproduction case and share with us?

I have just snippet what I shared above

> Does this crash the agent? Or does node spew an error and the agent keeps chugging along?

It crashes the agent, which then crashed our service completely

One more related problem - we are actually unable to disable obfuscation, because `obfuscate` function is called in SlowQuery constructor even if you set slow query settings to `raw`

https://github.com/newrelic/node-newrelic/blob/main/lib/db/slow-query.js#L14

**Comment by astormnewrelic** [comment] 2020-07-31 14:48
Thank you @tomashanacek -- 

> we are running some bigger sql queries with a lot of uuids

Would you be able to share some of those queries that trigger this crash? (with sensitive information scrubbed out, of course!).  We generally want to be able to reproduce the actual problem a user's facing in the agent before coming up with a fix.  

Without a reproducible test case, we often fix a similiar, but different, problem :)

**Comment by tomashanacek** [comment] 2020-08-01 09:47
@astormnewrelic so unfortunately I don't have specific query that caused the crash, because as soon as we identified obfuscation/slow-query is crashing our service we disable it and the query wasn't captured anywhere...

**Comment by tomashanacek** [comment] 2020-08-01 10:01
To my other question would it be possible to not call `obfuscate` function in `SlowQuery` when `record_sql` is set to 'raw'?

**Comment by tomashanacek** [comment] 2020-08-01 10:29
Ok so I found something, I would say it was caused by inserting big JSON data into Postgres.

```sql
INSERT INTO "Documents" ("data") VALUES (?)
```

where `?` is big JSON

**Comment by tomashanacek** [comment] 2020-08-01 10:44
I also played little bit with single quote regex and moving `''` or before `[^']` fixes the issue and still handles `''''` case

```javascript
/'(?:''|[^'])*?(?:\\'.*|'(?!'))/
```

**Comment by astormnewrelic** [comment] 2020-08-04 15:14
> To my other question would it be possible to not call obfuscate function in SlowQuery when record_sql is set to 'raw'?

The `raw` parameter is a legacy one that we're trying to move away from New Relic wide, so we're probably not going to be able to get a PR through that adds it to the slow sql queries.  Our best best is to focus on either fixing this regular expression, or moving to a different (possible parser based) solution.

**Comment by astormnewrelic** [comment] 2020-08-04 17:17
@tomashanacek I see -- so in `'(?:''|[^'])*?(?:\\'.*|'(?!'))` you've swapped the two conditions so that (in "PCRE comment format") instead of 

```
    /
        ...
        (?:
            [^'] | ''
        )
        ...
    /x
```

we have 

```
    /
        ...
        (?:
            '' | [^'] 
        )
        ...
    /x
```

That seems reasonable and the group still appears to capture "every single character that **isn't a quote** or _is two single quote characters_. 

In addition to this manual check of the semantics, our obfuscate suite seemed OK with this change.

    $ node test/unit/util/obfuscate-sql.test.js
    
Long term I think we (the Node Agent) will want to move away from regular expression based parsing.  In addition to these [runaway NFA expressions](https://stackoverflow.com/questions/3978438/dfa-vs-nfa-engines-what-is-the-difference-in-their-capabilities-and-limitations), working with these regular expressions is going to prove difficult long term.  That's probably best handled at a later date.  Short term this seems like a reasonable solution. 

@tomashanacek would you be comfortable making a PR into the agent that applies your regular expression _and_ creates a new test case for it?  In the test case we'd recommend building up a JSON object that's large enough to trigger the bug, serializing it, and then calling `obfuscate`. "No" is an acceptable answer -- but an external customer-led PR will probably be the fastest way to get this fix in.

**Comment by tomashanacek** [comment] 2020-08-05 09:33
@astormnewrelic just created a PR: https://github.com/newrelic/node-newrelic/pull/456

**Comment by astormnewrelic** [comment] 2020-08-17 15:16
Looks like we landed a fix for this in https://github.com/newrelic/node-newrelic/pull/456.  We're closing this out, but if this regular expression is still causing you problems please don't hesitate to keep the conversation going here or in another issue.

**Closed by astormnewrelic** 2020-08-17 15:16 UTC
Labels: bug
