### ISSUE TITLE
Shimmer.js causing ERR_REQUIRE_ESM error.

### ISSUE THREAD

**Issue by rohit-techolution** [newrelic/node-newrelic#1747] opened 2023-08-02 09:52 UTC
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

Shimmer.js causing 
```bash
/Users/rohitmahto/techo/ihm/playlists/node_modules/newrelic/lib/shimmer.js:307
[API]         const m = load.apply(this, arguments)
[API]                        ^
[API] Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/rohitmahto/techo/ihm/playlists/node_modules/apollo-angular/fesm2022/ngApollo.mjs not supported.
[API] Instead change the require of /Users/rohitmahto/techo/ihm/playlists/node_modules/apollo-angular/fesm2022/ngApollo.mjs to a dynamic import() which is available in all CommonJS modules.
```

[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT share sensitive information, whether personal, proprietary, or otherwise! )

## Expected Behavior
To successfully compile and run newrelic in typescript

[NOTE]: # ( Tell us what you expected to happen. )

## [Troubleshooting](https://discuss.newrelic.com/t/troubleshooting-frameworks/108787) or [NR Diag](https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/troubleshooting/new-relic-diagnostics) results

[NOTE]: # ( Provide any other relevant log data. )
[TIP]:  # ( Scrub logs and diagnostic information for sensitive information )

## Steps to Reproduce
Please use newrelic in a typescript project and use env way.
[NOTE]: # ( Please be as specific as possible. )
[TIP]:  # ( Link a sample application that demonstrates the issue. )

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )

* ex: Browser name and version: Chrome
* ex: Node version: 16, 18
* ex: Operating System and version: Mac 13

**Comment by mrickard** [comment] 2023-08-02 13:50
@rohit-techolution We're sorry to hear that you're having trouble. Would you be able to supply us with a repo containing a simple application that reproduces this behavior?

**Comment by bizob2828** [comment] 2023-09-13 16:26
@rohit-techolution I'm closing this because we cannot reproduce.  However, if you can provide steps to reproduce, please reopen.

**Closed by bizob2828** 2023-09-13 16:26 UTC
Labels: bug, needs-triage, more information
