### ISSUE TITLE
[NRWARN001] NewRelicWarning: Dropping log message, buffer would overflow warnings

### ISSUE THREAD

**Issue by TraGicCode** [newrelic/node-newrelic#1170] opened 2022-05-04 12:44 UTC
We are noticing the following warnings being shown when running our apollo-server graphql server under newrelic.

![image](https://user-images.githubusercontent.com/6224270/166683317-48051742-d9f3-4e06-84ff-eec96b979ec1.png)

Can someone explain and help me understand what is going on so i can understand if this is a bug with the agent or something our application is doing.

newrelic npm version:
8.10.0

@newrelic/apollo-server-plugin npm version:
1.2.3

**Comment by bizob2828** [comment] 2022-05-04 13:20
@TraGicCode what's your log level set to in the agent config? Also I noticed you're not on the latest version of Apollo plugin. Can you upgrade that to 1.3.0?

**Comment by TraGicCode** [comment] 2022-05-06 13:37
Hey @bizob2828 ,

I can upgrade but based on the release notes i don't expect the release to make a difference.

In regards to log level, it looks like it's configured to use trace

```
 logging: {
    /**
     * Level at which to log. 'trace' is most useful to New Relic when diagnosing
     * issues with the agent, 'info' and higher will impose the least overhead on
     * production applications.
     */
    level: 'trace',
  },
```

**Comment by bizob2828** [comment] 2022-05-06 13:41
@TraGicCode this could happen with trace level logging. We don't intend for customers to have this level set when running in production as it impacts performance. I recommend setting to info or below for production. So to answer your question it's not a bug but a warning you're hitting a limit for log lines in agent log buffer.

**Comment by TraGicCode** [comment] 2022-05-06 13:46
Hey @bizob2828 ,

This is awesome you pinpointed this.  We recently inherited this and would have never done this for production.

Could you provide some feedback on what things an application could exhibit from having trace logging on?  Could there be excessive memory over time or would you just expect slower performance?  

I also noticed the log file is in the GB's which is huge.  I'm not sure if the newrelic profiler is able to add content to the file without having to read the file into memory first.

Could you shed some insights on this?

**Comment by bizob2828** [comment] 2022-05-06 15:18
@TraGicCode you're probably incurring a lot of Disk I/O so an increase in CPU.  Also probably memory as it buffers log data.  If you set the log level to info the log size will go down significantly.  I'm going to close this issue.  If you have any other questions or need assistance with tuning your application, I recommend leveraging our support team over at support.newrelic.com.  They can help deep-dive into solving the problem. They will also ask to collect the necessary information which may or may not be sensitive (such as logs).

**Closed by bizob2828** 2022-05-06 15:18 UTC
Labels: bug, needs-triage

**Comment by mrtimp** [comment] 2024-09-02 20:43
Hopefully this helps someone. 

We noticed this periodically with long running Nextjs processes on AWS ECS Fargate. The container would fail with a very nondescript error and the exit code 133:

<img width="1418" alt="screenshot_ms_825" src="https://github.com/user-attachments/assets/37e02833-86e3-4c0e-ab5b-e5b1dc593308">

After changing from `logging.level = 'trace'` to `logging.level = 'info'` the container was more stable. It hasn't been running long enough for us to consider the issue fully resolved but is significantly more stable.
