### ISSUE TITLE
Facing 2 unit test failures on ppc64le architecture

### ISSUE THREAD

**Issue by vinodk99** [newrelic/node-newrelic#2520] opened 2024-08-27 06:38 UTC
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description
Facing 2 unit test failures on ppc64le architecture
[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT share sensitive information, whether personal, proprietary, or otherwise! )

## Expected Behavior
Tests need to passed successfully
[NOTE]: # ( Tell us what you expected to happen. )

## [Troubleshooting](https://discuss.newrelic.com/t/troubleshooting-frameworks/108787) or [NR Diag](https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/troubleshooting/new-relic-diagnostics) results

[NOTE]: # ( Provide any other relevant log data. )
[TIP]:  # ( Scrub logs and diagnostic information for sensitive information )
`
Failed tests:
/node-newrelic/test/unit/errors/error-collector.test.js
/node-newrelic/test/unit/instrumentation/http/http.test.js

Passed: 226
Failed: 2
Total: 228

real    3m30.233s
user    5m16.130s
sys     0m37.119s
`
## Steps to Reproduce

[NOTE]: # ( Please be as specific as possible. )
[TIP]:  # ( Link a sample application that demonstrates the issue. )

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )

* ex: Node version:v20.17.0
* ex: Operating System and version:5.14.0-70.13.1.el9_0.ppc64le

## Additional context

[TIP]:  # ( Add any other context about the problem here. For example, relevant community posts or support tickets. )

**Comment by bizob2828** [comment] 2024-08-27 19:49
Hi @vinodk99 we don't support this architecture, and I don't have any repro cases, can you please provide some steps to reproduce. But we may not fix because it's not a supported architecture. Do you have a reason why you're trying to run the tests on ppc64le?

**Comment by bizob2828** [comment] 2024-08-30 17:42
I'm going to close this. If you want to support ppc64le, please contribute the necessary fixes and we can consider landing those changes.

**Closed by bizob2828** 2024-08-30 17:42 UTC
Labels: feature-request, needs-triage
